# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_work_form.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_graph_work(object):
    def setupUi(self, graph_work):
        graph_work.setObjectName("graph_work")
        graph_work.resize(800, 600)
        self.gridLayout_5 = QtWidgets.QGridLayout(graph_work)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.graph_0 = QtWidgets.QWidget(graph_work)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graph_0.sizePolicy().hasHeightForWidth())
        self.graph_0.setSizePolicy(sizePolicy)
        self.graph_0.setObjectName("graph_0")
        self.gridLayout = QtWidgets.QGridLayout(self.graph_0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cobox_gph_0 = QtWidgets.QComboBox(self.graph_0)
        self.cobox_gph_0.setMinimumSize(QtCore.QSize(90, 20))
        self.cobox_gph_0.setMaximumSize(QtCore.QSize(90, 20))
        self.cobox_gph_0.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cobox_gph_0.setObjectName("cobox_gph_0")
        self.cobox_gph_0.addItem("")
        self.cobox_gph_0.addItem("")
        self.cobox_gph_0.addItem("")
        self.cobox_gph_0.addItem("")
        self.gridLayout.addWidget(self.cobox_gph_0, 0, 0, 1, 1)
        self.cobox_chl_0 = QtWidgets.QComboBox(self.graph_0)
        self.cobox_chl_0.setMinimumSize(QtCore.QSize(60, 20))
        self.cobox_chl_0.setMaximumSize(QtCore.QSize(60, 20))
        self.cobox_chl_0.setObjectName("cobox_chl_0")
        self.cobox_chl_0.addItem("")
        self.cobox_chl_0.addItem("")
        self.cobox_chl_0.addItem("")
        self.cobox_chl_0.addItem("")
        self.gridLayout.addWidget(self.cobox_chl_0, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(230, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.graph_ctx_0 = QtWidgets.QWidget(self.graph_0)
        self.graph_ctx_0.setObjectName("graph_ctx_0")
        self.gridLayout.addWidget(self.graph_ctx_0, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.graph_0, 0, 0, 1, 1)
        self.graph_1 = QtWidgets.QWidget(graph_work)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graph_1.sizePolicy().hasHeightForWidth())
        self.graph_1.setSizePolicy(sizePolicy)
        self.graph_1.setObjectName("graph_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.graph_1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cobox_gph_1 = QtWidgets.QComboBox(self.graph_1)
        self.cobox_gph_1.setMinimumSize(QtCore.QSize(90, 20))
        self.cobox_gph_1.setMaximumSize(QtCore.QSize(90, 20))
        self.cobox_gph_1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cobox_gph_1.setObjectName("cobox_gph_1")
        self.cobox_gph_1.addItem("")
        self.cobox_gph_1.addItem("")
        self.cobox_gph_1.addItem("")
        self.cobox_gph_1.addItem("")
        self.gridLayout_2.addWidget(self.cobox_gph_1, 0, 0, 1, 1)
        self.cobox_chl_1 = QtWidgets.QComboBox(self.graph_1)
        self.cobox_chl_1.setMinimumSize(QtCore.QSize(60, 20))
        self.cobox_chl_1.setMaximumSize(QtCore.QSize(60, 20))
        self.cobox_chl_1.setObjectName("cobox_chl_1")
        self.cobox_chl_1.addItem("")
        self.cobox_chl_1.addItem("")
        self.cobox_chl_1.addItem("")
        self.cobox_chl_1.addItem("")
        self.gridLayout_2.addWidget(self.cobox_chl_1, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.graph_ctx_1 = QtWidgets.QWidget(self.graph_1)
        self.graph_ctx_1.setObjectName("graph_ctx_1")
        self.gridLayout_2.addWidget(self.graph_ctx_1, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.graph_1, 0, 1, 1, 1)
        self.graph_2 = QtWidgets.QWidget(graph_work)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graph_2.sizePolicy().hasHeightForWidth())
        self.graph_2.setSizePolicy(sizePolicy)
        self.graph_2.setObjectName("graph_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.graph_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cobox_gph_2 = QtWidgets.QComboBox(self.graph_2)
        self.cobox_gph_2.setMinimumSize(QtCore.QSize(90, 20))
        self.cobox_gph_2.setMaximumSize(QtCore.QSize(90, 20))
        self.cobox_gph_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cobox_gph_2.setObjectName("cobox_gph_2")
        self.cobox_gph_2.addItem("")
        self.cobox_gph_2.addItem("")
        self.cobox_gph_2.addItem("")
        self.cobox_gph_2.addItem("")
        self.gridLayout_3.addWidget(self.cobox_gph_2, 0, 0, 1, 1)
        self.cobox_chl_2 = QtWidgets.QComboBox(self.graph_2)
        self.cobox_chl_2.setMinimumSize(QtCore.QSize(60, 20))
        self.cobox_chl_2.setMaximumSize(QtCore.QSize(60, 20))
        self.cobox_chl_2.setObjectName("cobox_chl_2")
        self.cobox_chl_2.addItem("")
        self.cobox_chl_2.addItem("")
        self.cobox_chl_2.addItem("")
        self.cobox_chl_2.addItem("")
        self.gridLayout_3.addWidget(self.cobox_chl_2, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 2, 1, 1)
        self.graph_ctx_2 = QtWidgets.QWidget(self.graph_2)
        self.graph_ctx_2.setObjectName("graph_ctx_2")
        self.gridLayout_3.addWidget(self.graph_ctx_2, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.graph_2, 1, 0, 1, 1)
        self.graph_3 = QtWidgets.QWidget(graph_work)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graph_3.sizePolicy().hasHeightForWidth())
        self.graph_3.setSizePolicy(sizePolicy)
        self.graph_3.setObjectName("graph_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.graph_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cobox_gph_3 = QtWidgets.QComboBox(self.graph_3)
        self.cobox_gph_3.setMinimumSize(QtCore.QSize(90, 20))
        self.cobox_gph_3.setMaximumSize(QtCore.QSize(90, 20))
        self.cobox_gph_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cobox_gph_3.setObjectName("cobox_gph_3")
        self.cobox_gph_3.addItem("")
        self.cobox_gph_3.addItem("")
        self.cobox_gph_3.addItem("")
        self.cobox_gph_3.addItem("")
        self.gridLayout_4.addWidget(self.cobox_gph_3, 0, 0, 1, 1)
        self.cobox_chl_3 = QtWidgets.QComboBox(self.graph_3)
        self.cobox_chl_3.setMinimumSize(QtCore.QSize(60, 20))
        self.cobox_chl_3.setMaximumSize(QtCore.QSize(60, 20))
        self.cobox_chl_3.setObjectName("cobox_chl_3")
        self.cobox_chl_3.addItem("")
        self.cobox_chl_3.addItem("")
        self.cobox_chl_3.addItem("")
        self.cobox_chl_3.addItem("")
        self.gridLayout_4.addWidget(self.cobox_chl_3, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 2, 1, 1)
        self.graph_ctx_3 = QtWidgets.QWidget(self.graph_3)
        self.graph_ctx_3.setObjectName("graph_ctx_3")
        self.gridLayout_4.addWidget(self.graph_ctx_3, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.graph_3, 1, 1, 1, 1)

        self.retranslateUi(graph_work)
        QtCore.QMetaObject.connectSlotsByName(graph_work)

    def retranslateUi(self, graph_work):
        _translate = QtCore.QCoreApplication.translate
        graph_work.setWindowTitle(_translate("graph_work", "Form"))
        self.cobox_gph_0.setItemText(0, _translate("graph_work", "Normal"))
        self.cobox_gph_0.setItemText(1, _translate("graph_work", "Vertical"))
        self.cobox_gph_0.setItemText(2, _translate("graph_work", "Horizontal"))
        self.cobox_gph_0.setItemText(3, _translate("graph_work", "Integrated"))
        self.cobox_chl_0.setItemText(0, _translate("graph_work", "Full"))
        self.cobox_chl_0.setItemText(1, _translate("graph_work", "0"))
        self.cobox_chl_0.setItemText(2, _translate("graph_work", "1"))
        self.cobox_chl_0.setItemText(3, _translate("graph_work", "2"))
        self.cobox_gph_1.setItemText(0, _translate("graph_work", "Normal"))
        self.cobox_gph_1.setItemText(1, _translate("graph_work", "Vertical"))
        self.cobox_gph_1.setItemText(2, _translate("graph_work", "Horizontal"))
        self.cobox_gph_1.setItemText(3, _translate("graph_work", "Integrated"))
        self.cobox_chl_1.setItemText(0, _translate("graph_work", "Full"))
        self.cobox_chl_1.setItemText(1, _translate("graph_work", "0"))
        self.cobox_chl_1.setItemText(2, _translate("graph_work", "1"))
        self.cobox_chl_1.setItemText(3, _translate("graph_work", "2"))
        self.cobox_gph_2.setItemText(0, _translate("graph_work", "Normal"))
        self.cobox_gph_2.setItemText(1, _translate("graph_work", "Vertical"))
        self.cobox_gph_2.setItemText(2, _translate("graph_work", "Horizontal"))
        self.cobox_gph_2.setItemText(3, _translate("graph_work", "Integrated"))
        self.cobox_chl_2.setItemText(0, _translate("graph_work", "Full"))
        self.cobox_chl_2.setItemText(1, _translate("graph_work", "0"))
        self.cobox_chl_2.setItemText(2, _translate("graph_work", "1"))
        self.cobox_chl_2.setItemText(3, _translate("graph_work", "2"))
        self.cobox_gph_3.setItemText(0, _translate("graph_work", "Normal"))
        self.cobox_gph_3.setItemText(1, _translate("graph_work", "Vertical"))
        self.cobox_gph_3.setItemText(2, _translate("graph_work", "Horizontal"))
        self.cobox_gph_3.setItemText(3, _translate("graph_work", "Integrated"))
        self.cobox_chl_3.setItemText(0, _translate("graph_work", "Full"))
        self.cobox_chl_3.setItemText(1, _translate("graph_work", "0"))
        self.cobox_chl_3.setItemText(2, _translate("graph_work", "1"))
        self.cobox_chl_3.setItemText(3, _translate("graph_work", "2"))


