# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_views_form.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_graph_views(object):
    def setupUi(self, graph_views):
        graph_views.setObjectName("graph_views")
        graph_views.resize(800, 600)
        self.graph_view_0 = QtWidgets.QWidget(graph_views)
        self.graph_view_0.setGeometry(QtCore.QRect(11, 11, 386, 286))
        self.graph_view_0.setAutoFillBackground(True)
        self.graph_view_0.setObjectName("graph_view_0")
        self.pbtn_move_up_0 = QtWidgets.QPushButton(self.graph_view_0)
        self.pbtn_move_up_0.setGeometry(QtCore.QRect(100, 0, 20, 20))
        self.pbtn_move_up_0.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_up_0.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_up_0.setObjectName("pbtn_move_up_0")
        self.pbtn_zoom_out_0 = QtWidgets.QPushButton(self.graph_view_0)
        self.pbtn_zoom_out_0.setGeometry(QtCore.QRect(120, 0, 20, 20))
        self.pbtn_zoom_out_0.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_out_0.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_out_0.setObjectName("pbtn_zoom_out_0")
        self.pbtn_move_down_0 = QtWidgets.QPushButton(self.graph_view_0)
        self.pbtn_move_down_0.setGeometry(QtCore.QRect(100, 40, 20, 20))
        self.pbtn_move_down_0.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_down_0.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_down_0.setObjectName("pbtn_move_down_0")
        self.cobox_chl_0 = QtWidgets.QComboBox(self.graph_view_0)
        self.cobox_chl_0.setGeometry(QtCore.QRect(35, 0, 35, 20))
        self.cobox_chl_0.setMinimumSize(QtCore.QSize(35, 20))
        self.cobox_chl_0.setMaximumSize(QtCore.QSize(35, 20))
        self.cobox_chl_0.setObjectName("cobox_chl_0")
        self.cobox_chl_0.addItem("")
        self.cobox_chl_0.addItem("")
        self.cobox_chl_0.addItem("")
        self.cobox_chl_0.addItem("")
        self.pbtn_move_left_0 = QtWidgets.QPushButton(self.graph_view_0)
        self.pbtn_move_left_0.setGeometry(QtCore.QRect(80, 20, 20, 20))
        self.pbtn_move_left_0.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_left_0.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_left_0.setObjectName("pbtn_move_left_0")
        self.cobox_gph_0 = QtWidgets.QComboBox(self.graph_view_0)
        self.cobox_gph_0.setGeometry(QtCore.QRect(0, 0, 35, 20))
        self.cobox_gph_0.setMinimumSize(QtCore.QSize(35, 20))
        self.cobox_gph_0.setMaximumSize(QtCore.QSize(35, 20))
        self.cobox_gph_0.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cobox_gph_0.setObjectName("cobox_gph_0")
        self.cobox_gph_0.addItem("")
        self.cobox_gph_0.addItem("")
        self.cobox_gph_0.addItem("")
        self.cobox_gph_0.addItem("")
        self.pbtn_zoom_in_0 = QtWidgets.QPushButton(self.graph_view_0)
        self.pbtn_zoom_in_0.setGeometry(QtCore.QRect(80, 0, 20, 20))
        self.pbtn_zoom_in_0.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_in_0.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_in_0.setObjectName("pbtn_zoom_in_0")
        self.pbtn_move_right_0 = QtWidgets.QPushButton(self.graph_view_0)
        self.pbtn_move_right_0.setGeometry(QtCore.QRect(120, 20, 20, 20))
        self.pbtn_move_right_0.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_right_0.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_right_0.setObjectName("pbtn_move_right_0")
        self.pbtn_return_home_0 = QtWidgets.QPushButton(self.graph_view_0)
        self.pbtn_return_home_0.setGeometry(QtCore.QRect(100, 20, 20, 20))
        self.pbtn_return_home_0.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_return_home_0.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_return_home_0.setObjectName("pbtn_return_home_0")
        self.graph_label_0 = QtWidgets.QLabel(self.graph_view_0)
        self.graph_label_0.setGeometry(QtCore.QRect(60, 70, 111, 51))
        self.graph_label_0.setText("")
        self.graph_label_0.setAlignment(QtCore.Qt.AlignCenter)
        self.graph_label_0.setObjectName("graph_label_0")
        self.graph_label_0.raise_()
        self.pbtn_move_up_0.raise_()
        self.pbtn_zoom_out_0.raise_()
        self.pbtn_move_down_0.raise_()
        self.cobox_chl_0.raise_()
        self.pbtn_move_left_0.raise_()
        self.cobox_gph_0.raise_()
        self.pbtn_zoom_in_0.raise_()
        self.pbtn_move_right_0.raise_()
        self.pbtn_return_home_0.raise_()
        self.graph_view_1 = QtWidgets.QWidget(graph_views)
        self.graph_view_1.setGeometry(QtCore.QRect(404, 11, 385, 286))
        self.graph_view_1.setAutoFillBackground(True)
        self.graph_view_1.setObjectName("graph_view_1")
        self.pbtn_move_up_1 = QtWidgets.QPushButton(self.graph_view_1)
        self.pbtn_move_up_1.setGeometry(QtCore.QRect(100, 0, 20, 20))
        self.pbtn_move_up_1.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_up_1.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_up_1.setObjectName("pbtn_move_up_1")
        self.pbtn_zoom_out_1 = QtWidgets.QPushButton(self.graph_view_1)
        self.pbtn_zoom_out_1.setGeometry(QtCore.QRect(120, 0, 20, 20))
        self.pbtn_zoom_out_1.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_out_1.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_out_1.setObjectName("pbtn_zoom_out_1")
        self.pbtn_move_down_1 = QtWidgets.QPushButton(self.graph_view_1)
        self.pbtn_move_down_1.setGeometry(QtCore.QRect(100, 40, 20, 20))
        self.pbtn_move_down_1.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_down_1.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_down_1.setObjectName("pbtn_move_down_1")
        self.cobox_chl_1 = QtWidgets.QComboBox(self.graph_view_1)
        self.cobox_chl_1.setGeometry(QtCore.QRect(35, 0, 35, 20))
        self.cobox_chl_1.setMinimumSize(QtCore.QSize(35, 20))
        self.cobox_chl_1.setMaximumSize(QtCore.QSize(35, 20))
        self.cobox_chl_1.setObjectName("cobox_chl_1")
        self.cobox_chl_1.addItem("")
        self.cobox_chl_1.addItem("")
        self.cobox_chl_1.addItem("")
        self.cobox_chl_1.addItem("")
        self.pbtn_move_left_1 = QtWidgets.QPushButton(self.graph_view_1)
        self.pbtn_move_left_1.setGeometry(QtCore.QRect(80, 20, 20, 20))
        self.pbtn_move_left_1.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_left_1.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_left_1.setObjectName("pbtn_move_left_1")
        self.cobox_gph_1 = QtWidgets.QComboBox(self.graph_view_1)
        self.cobox_gph_1.setGeometry(QtCore.QRect(0, 0, 35, 20))
        self.cobox_gph_1.setMinimumSize(QtCore.QSize(35, 20))
        self.cobox_gph_1.setMaximumSize(QtCore.QSize(35, 20))
        self.cobox_gph_1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cobox_gph_1.setObjectName("cobox_gph_1")
        self.cobox_gph_1.addItem("")
        self.cobox_gph_1.addItem("")
        self.cobox_gph_1.addItem("")
        self.cobox_gph_1.addItem("")
        self.pbtn_zoom_in_1 = QtWidgets.QPushButton(self.graph_view_1)
        self.pbtn_zoom_in_1.setGeometry(QtCore.QRect(80, 0, 20, 20))
        self.pbtn_zoom_in_1.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_in_1.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_in_1.setObjectName("pbtn_zoom_in_1")
        self.pbtn_move_right_1 = QtWidgets.QPushButton(self.graph_view_1)
        self.pbtn_move_right_1.setGeometry(QtCore.QRect(120, 20, 20, 20))
        self.pbtn_move_right_1.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_right_1.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_right_1.setObjectName("pbtn_move_right_1")
        self.pbtn_return_home_1 = QtWidgets.QPushButton(self.graph_view_1)
        self.pbtn_return_home_1.setGeometry(QtCore.QRect(100, 20, 20, 20))
        self.pbtn_return_home_1.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_return_home_1.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_return_home_1.setObjectName("pbtn_return_home_1")
        self.graph_label_1 = QtWidgets.QLabel(self.graph_view_1)
        self.graph_label_1.setGeometry(QtCore.QRect(60, 70, 111, 51))
        self.graph_label_1.setText("")
        self.graph_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.graph_label_1.setObjectName("graph_label_1")
        self.graph_label_1.raise_()
        self.pbtn_move_up_1.raise_()
        self.pbtn_zoom_out_1.raise_()
        self.pbtn_move_down_1.raise_()
        self.cobox_chl_1.raise_()
        self.pbtn_move_left_1.raise_()
        self.cobox_gph_1.raise_()
        self.pbtn_zoom_in_1.raise_()
        self.pbtn_move_right_1.raise_()
        self.pbtn_return_home_1.raise_()
        self.graph_view_2 = QtWidgets.QWidget(graph_views)
        self.graph_view_2.setGeometry(QtCore.QRect(11, 304, 386, 285))
        self.graph_view_2.setAutoFillBackground(True)
        self.graph_view_2.setObjectName("graph_view_2")
        self.pbtn_move_up_2 = QtWidgets.QPushButton(self.graph_view_2)
        self.pbtn_move_up_2.setGeometry(QtCore.QRect(100, 0, 20, 20))
        self.pbtn_move_up_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_up_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_up_2.setObjectName("pbtn_move_up_2")
        self.pbtn_zoom_out_2 = QtWidgets.QPushButton(self.graph_view_2)
        self.pbtn_zoom_out_2.setGeometry(QtCore.QRect(120, 0, 20, 20))
        self.pbtn_zoom_out_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_out_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_out_2.setObjectName("pbtn_zoom_out_2")
        self.pbtn_move_down_2 = QtWidgets.QPushButton(self.graph_view_2)
        self.pbtn_move_down_2.setGeometry(QtCore.QRect(100, 40, 20, 20))
        self.pbtn_move_down_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_down_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_down_2.setObjectName("pbtn_move_down_2")
        self.cobox_chl_2 = QtWidgets.QComboBox(self.graph_view_2)
        self.cobox_chl_2.setGeometry(QtCore.QRect(35, 0, 35, 20))
        self.cobox_chl_2.setMinimumSize(QtCore.QSize(35, 20))
        self.cobox_chl_2.setMaximumSize(QtCore.QSize(35, 20))
        self.cobox_chl_2.setObjectName("cobox_chl_2")
        self.cobox_chl_2.addItem("")
        self.cobox_chl_2.addItem("")
        self.cobox_chl_2.addItem("")
        self.cobox_chl_2.addItem("")
        self.pbtn_move_left_2 = QtWidgets.QPushButton(self.graph_view_2)
        self.pbtn_move_left_2.setGeometry(QtCore.QRect(80, 20, 20, 20))
        self.pbtn_move_left_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_left_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_left_2.setObjectName("pbtn_move_left_2")
        self.cobox_gph_2 = QtWidgets.QComboBox(self.graph_view_2)
        self.cobox_gph_2.setGeometry(QtCore.QRect(0, 0, 35, 20))
        self.cobox_gph_2.setMinimumSize(QtCore.QSize(35, 20))
        self.cobox_gph_2.setMaximumSize(QtCore.QSize(35, 20))
        self.cobox_gph_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cobox_gph_2.setObjectName("cobox_gph_2")
        self.cobox_gph_2.addItem("")
        self.cobox_gph_2.addItem("")
        self.cobox_gph_2.addItem("")
        self.cobox_gph_2.addItem("")
        self.pbtn_zoom_in_2 = QtWidgets.QPushButton(self.graph_view_2)
        self.pbtn_zoom_in_2.setGeometry(QtCore.QRect(80, 0, 20, 20))
        self.pbtn_zoom_in_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_in_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_in_2.setObjectName("pbtn_zoom_in_2")
        self.pbtn_move_right_2 = QtWidgets.QPushButton(self.graph_view_2)
        self.pbtn_move_right_2.setGeometry(QtCore.QRect(120, 20, 20, 20))
        self.pbtn_move_right_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_right_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_right_2.setObjectName("pbtn_move_right_2")
        self.pbtn_return_home_2 = QtWidgets.QPushButton(self.graph_view_2)
        self.pbtn_return_home_2.setGeometry(QtCore.QRect(100, 20, 20, 20))
        self.pbtn_return_home_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_return_home_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_return_home_2.setObjectName("pbtn_return_home_2")
        self.graph_label_2 = QtWidgets.QLabel(self.graph_view_2)
        self.graph_label_2.setGeometry(QtCore.QRect(60, 70, 111, 51))
        self.graph_label_2.setText("")
        self.graph_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.graph_label_2.setObjectName("graph_label_2")
        self.graph_label_2.raise_()
        self.pbtn_move_up_2.raise_()
        self.pbtn_zoom_out_2.raise_()
        self.pbtn_move_down_2.raise_()
        self.cobox_chl_2.raise_()
        self.pbtn_move_left_2.raise_()
        self.cobox_gph_2.raise_()
        self.pbtn_zoom_in_2.raise_()
        self.pbtn_move_right_2.raise_()
        self.pbtn_return_home_2.raise_()
        self.graph_view_3 = QtWidgets.QWidget(graph_views)
        self.graph_view_3.setGeometry(QtCore.QRect(404, 304, 385, 285))
        self.graph_view_3.setAutoFillBackground(True)
        self.graph_view_3.setObjectName("graph_view_3")
        self.pbtn_move_up_3 = QtWidgets.QPushButton(self.graph_view_3)
        self.pbtn_move_up_3.setGeometry(QtCore.QRect(100, 0, 20, 20))
        self.pbtn_move_up_3.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_up_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_up_3.setObjectName("pbtn_move_up_3")
        self.pbtn_zoom_out_3 = QtWidgets.QPushButton(self.graph_view_3)
        self.pbtn_zoom_out_3.setGeometry(QtCore.QRect(120, 0, 20, 20))
        self.pbtn_zoom_out_3.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_out_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_out_3.setObjectName("pbtn_zoom_out_3")
        self.pbtn_move_down_3 = QtWidgets.QPushButton(self.graph_view_3)
        self.pbtn_move_down_3.setGeometry(QtCore.QRect(100, 40, 20, 20))
        self.pbtn_move_down_3.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_down_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_down_3.setObjectName("pbtn_move_down_3")
        self.cobox_chl_3 = QtWidgets.QComboBox(self.graph_view_3)
        self.cobox_chl_3.setGeometry(QtCore.QRect(35, 0, 35, 20))
        self.cobox_chl_3.setMinimumSize(QtCore.QSize(35, 20))
        self.cobox_chl_3.setMaximumSize(QtCore.QSize(35, 20))
        self.cobox_chl_3.setObjectName("cobox_chl_3")
        self.cobox_chl_3.addItem("")
        self.cobox_chl_3.addItem("")
        self.cobox_chl_3.addItem("")
        self.cobox_chl_3.addItem("")
        self.pbtn_move_left_3 = QtWidgets.QPushButton(self.graph_view_3)
        self.pbtn_move_left_3.setGeometry(QtCore.QRect(80, 20, 20, 20))
        self.pbtn_move_left_3.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_left_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_left_3.setObjectName("pbtn_move_left_3")
        self.cobox_gph_3 = QtWidgets.QComboBox(self.graph_view_3)
        self.cobox_gph_3.setGeometry(QtCore.QRect(0, 0, 35, 20))
        self.cobox_gph_3.setMinimumSize(QtCore.QSize(35, 20))
        self.cobox_gph_3.setMaximumSize(QtCore.QSize(35, 20))
        self.cobox_gph_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cobox_gph_3.setObjectName("cobox_gph_3")
        self.cobox_gph_3.addItem("")
        self.cobox_gph_3.addItem("")
        self.cobox_gph_3.addItem("")
        self.cobox_gph_3.addItem("")
        self.pbtn_zoom_in_3 = QtWidgets.QPushButton(self.graph_view_3)
        self.pbtn_zoom_in_3.setGeometry(QtCore.QRect(80, 0, 20, 20))
        self.pbtn_zoom_in_3.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_in_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_zoom_in_3.setObjectName("pbtn_zoom_in_3")
        self.pbtn_move_right_3 = QtWidgets.QPushButton(self.graph_view_3)
        self.pbtn_move_right_3.setGeometry(QtCore.QRect(120, 20, 20, 20))
        self.pbtn_move_right_3.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_move_right_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_move_right_3.setObjectName("pbtn_move_right_3")
        self.pbtn_return_home_3 = QtWidgets.QPushButton(self.graph_view_3)
        self.pbtn_return_home_3.setGeometry(QtCore.QRect(100, 20, 20, 20))
        self.pbtn_return_home_3.setMinimumSize(QtCore.QSize(20, 20))
        self.pbtn_return_home_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pbtn_return_home_3.setObjectName("pbtn_return_home_3")
        self.graph_label_3 = QtWidgets.QLabel(self.graph_view_3)
        self.graph_label_3.setGeometry(QtCore.QRect(60, 70, 111, 51))
        self.graph_label_3.setText("")
        self.graph_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.graph_label_3.setObjectName("graph_label_3")
        self.graph_label_3.raise_()
        self.pbtn_move_up_3.raise_()
        self.pbtn_zoom_out_3.raise_()
        self.pbtn_move_down_3.raise_()
        self.cobox_chl_3.raise_()
        self.pbtn_move_left_3.raise_()
        self.cobox_gph_3.raise_()
        self.pbtn_zoom_in_3.raise_()
        self.pbtn_move_right_3.raise_()
        self.pbtn_return_home_3.raise_()

        self.retranslateUi(graph_views)
        QtCore.QMetaObject.connectSlotsByName(graph_views)

    def retranslateUi(self, graph_views):
        _translate = QtCore.QCoreApplication.translate
        graph_views.setWindowTitle(_translate("graph_views", "Form"))
        self.pbtn_move_up_0.setText(_translate("graph_views", "U"))
        self.pbtn_zoom_out_0.setText(_translate("graph_views", "-"))
        self.pbtn_move_down_0.setText(_translate("graph_views", "D"))
        self.cobox_chl_0.setItemText(0, _translate("graph_views", "A"))
        self.cobox_chl_0.setItemText(1, _translate("graph_views", "1"))
        self.cobox_chl_0.setItemText(2, _translate("graph_views", "2"))
        self.cobox_chl_0.setItemText(3, _translate("graph_views", "3"))
        self.pbtn_move_left_0.setText(_translate("graph_views", "L"))
        self.cobox_gph_0.setItemText(0, _translate("graph_views", "N"))
        self.cobox_gph_0.setItemText(1, _translate("graph_views", "V"))
        self.cobox_gph_0.setItemText(2, _translate("graph_views", "H"))
        self.cobox_gph_0.setItemText(3, _translate("graph_views", "F"))
        self.pbtn_zoom_in_0.setText(_translate("graph_views", "+"))
        self.pbtn_move_right_0.setText(_translate("graph_views", "R"))
        self.pbtn_return_home_0.setText(_translate("graph_views", "H"))
        self.pbtn_move_up_1.setText(_translate("graph_views", "U"))
        self.pbtn_zoom_out_1.setText(_translate("graph_views", "-"))
        self.pbtn_move_down_1.setText(_translate("graph_views", "D"))
        self.cobox_chl_1.setItemText(0, _translate("graph_views", "A"))
        self.cobox_chl_1.setItemText(1, _translate("graph_views", "1"))
        self.cobox_chl_1.setItemText(2, _translate("graph_views", "2"))
        self.cobox_chl_1.setItemText(3, _translate("graph_views", "3"))
        self.pbtn_move_left_1.setText(_translate("graph_views", "L"))
        self.cobox_gph_1.setItemText(0, _translate("graph_views", "N"))
        self.cobox_gph_1.setItemText(1, _translate("graph_views", "V"))
        self.cobox_gph_1.setItemText(2, _translate("graph_views", "H"))
        self.cobox_gph_1.setItemText(3, _translate("graph_views", "F"))
        self.pbtn_zoom_in_1.setText(_translate("graph_views", "+"))
        self.pbtn_move_right_1.setText(_translate("graph_views", "R"))
        self.pbtn_return_home_1.setText(_translate("graph_views", "H"))
        self.pbtn_move_up_2.setText(_translate("graph_views", "U"))
        self.pbtn_zoom_out_2.setText(_translate("graph_views", "-"))
        self.pbtn_move_down_2.setText(_translate("graph_views", "D"))
        self.cobox_chl_2.setItemText(0, _translate("graph_views", "A"))
        self.cobox_chl_2.setItemText(1, _translate("graph_views", "1"))
        self.cobox_chl_2.setItemText(2, _translate("graph_views", "2"))
        self.cobox_chl_2.setItemText(3, _translate("graph_views", "3"))
        self.pbtn_move_left_2.setText(_translate("graph_views", "L"))
        self.cobox_gph_2.setItemText(0, _translate("graph_views", "N"))
        self.cobox_gph_2.setItemText(1, _translate("graph_views", "V"))
        self.cobox_gph_2.setItemText(2, _translate("graph_views", "H"))
        self.cobox_gph_2.setItemText(3, _translate("graph_views", "F"))
        self.pbtn_zoom_in_2.setText(_translate("graph_views", "+"))
        self.pbtn_move_right_2.setText(_translate("graph_views", "R"))
        self.pbtn_return_home_2.setText(_translate("graph_views", "H"))
        self.pbtn_move_up_3.setText(_translate("graph_views", "U"))
        self.pbtn_zoom_out_3.setText(_translate("graph_views", "-"))
        self.pbtn_move_down_3.setText(_translate("graph_views", "D"))
        self.cobox_chl_3.setItemText(0, _translate("graph_views", "A"))
        self.cobox_chl_3.setItemText(1, _translate("graph_views", "1"))
        self.cobox_chl_3.setItemText(2, _translate("graph_views", "2"))
        self.cobox_chl_3.setItemText(3, _translate("graph_views", "3"))
        self.pbtn_move_left_3.setText(_translate("graph_views", "L"))
        self.cobox_gph_3.setItemText(0, _translate("graph_views", "N"))
        self.cobox_gph_3.setItemText(1, _translate("graph_views", "V"))
        self.cobox_gph_3.setItemText(2, _translate("graph_views", "H"))
        self.cobox_gph_3.setItemText(3, _translate("graph_views", "F"))
        self.pbtn_zoom_in_3.setText(_translate("graph_views", "+"))
        self.pbtn_move_right_3.setText(_translate("graph_views", "R"))
        self.pbtn_return_home_3.setText(_translate("graph_views", "H"))


