# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.toolbox = QtWidgets.QWidget(self.splitter)
        self.toolbox.setMinimumSize(QtCore.QSize(180, 0))
        self.toolbox.setObjectName("toolbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.toolbox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbox_Rule = QtWidgets.QGroupBox(self.toolbox)
        self.gbox_Rule.setObjectName("gbox_Rule")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbox_Rule)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rbtn_analogous = QtWidgets.QRadioButton(self.gbox_Rule)
        self.rbtn_analogous.setChecked(True)
        self.rbtn_analogous.setObjectName("rbtn_analogous")
        self.gridLayout_3.addWidget(self.rbtn_analogous, 0, 0, 1, 1)
        self.rbtn_monochromatic = QtWidgets.QRadioButton(self.gbox_Rule)
        self.rbtn_monochromatic.setObjectName("rbtn_monochromatic")
        self.gridLayout_3.addWidget(self.rbtn_monochromatic, 1, 0, 1, 2)
        self.rbtn_triad = QtWidgets.QRadioButton(self.gbox_Rule)
        self.rbtn_triad.setObjectName("rbtn_triad")
        self.gridLayout_3.addWidget(self.rbtn_triad, 2, 0, 1, 1)
        self.rbtn_tetrad = QtWidgets.QRadioButton(self.gbox_Rule)
        self.rbtn_tetrad.setObjectName("rbtn_tetrad")
        self.gridLayout_3.addWidget(self.rbtn_tetrad, 3, 0, 1, 1)
        self.rbtn_pentad = QtWidgets.QRadioButton(self.gbox_Rule)
        self.rbtn_pentad.setObjectName("rbtn_pentad")
        self.gridLayout_3.addWidget(self.rbtn_pentad, 4, 0, 1, 1)
        self.rbtn_complementary = QtWidgets.QRadioButton(self.gbox_Rule)
        self.rbtn_complementary.setObjectName("rbtn_complementary")
        self.gridLayout_3.addWidget(self.rbtn_complementary, 5, 0, 1, 2)
        self.rbtn_shades = QtWidgets.QRadioButton(self.gbox_Rule)
        self.rbtn_shades.setObjectName("rbtn_shades")
        self.gridLayout_3.addWidget(self.rbtn_shades, 6, 0, 1, 1)
        self.rbtn_custom = QtWidgets.QRadioButton(self.gbox_Rule)
        self.rbtn_custom.setObjectName("rbtn_custom")
        self.gridLayout_3.addWidget(self.rbtn_custom, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 8, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 7, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbox_Rule)
        self.gbox_View = QtWidgets.QGroupBox(self.toolbox)
        self.gbox_View.setObjectName("gbox_View")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gbox_View)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rbtn_individual = QtWidgets.QRadioButton(self.gbox_View)
        self.rbtn_individual.setChecked(False)
        self.rbtn_individual.setObjectName("rbtn_individual")
        self.gridLayout_5.addWidget(self.rbtn_individual, 0, 0, 1, 1)
        self.rbtn_referential = QtWidgets.QRadioButton(self.gbox_View)
        self.rbtn_referential.setObjectName("rbtn_referential")
        self.gridLayout_5.addWidget(self.rbtn_referential, 1, 0, 1, 2)
        self.rbtn_overall = QtWidgets.QRadioButton(self.gbox_View)
        self.rbtn_overall.setChecked(True)
        self.rbtn_overall.setObjectName("rbtn_overall")
        self.gridLayout_5.addWidget(self.rbtn_overall, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.gbox_View)
        self.workspace = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.workspace.sizePolicy().hasHeightForWidth())
        self.workspace.setSizePolicy(sizePolicy)
        self.workspace.setMinimumSize(QtCore.QSize(400, 350))
        self.workspace.setObjectName("workspace")
        self.property = QtWidgets.QWidget(self.splitter)
        self.property.setMinimumSize(QtCore.QSize(180, 0))
        self.property.setObjectName("property")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.property)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbox_Operation = QtWidgets.QGroupBox(self.property)
        self.gbox_Operation.setObjectName("gbox_Operation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbox_Operation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pbtn_Import = QtWidgets.QPushButton(self.gbox_Operation)
        self.pbtn_Import.setObjectName("pbtn_Import")
        self.gridLayout_2.addWidget(self.pbtn_Import, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(31, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)
        self.pbtn_Export = QtWidgets.QPushButton(self.gbox_Operation)
        self.pbtn_Export.setObjectName("pbtn_Export")
        self.gridLayout_2.addWidget(self.pbtn_Export, 1, 0, 1, 1)
        self.pbtn_Create = QtWidgets.QPushButton(self.gbox_Operation)
        self.pbtn_Create.setObjectName("pbtn_Create")
        self.gridLayout_2.addWidget(self.pbtn_Create, 2, 0, 1, 1)
        self.pbtn_Extract = QtWidgets.QPushButton(self.gbox_Operation)
        self.pbtn_Extract.setObjectName("pbtn_Extract")
        self.gridLayout_2.addWidget(self.pbtn_Extract, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 137, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.gbox_Operation)
        self.gbox_Mode = QtWidgets.QGroupBox(self.property)
        self.gbox_Mode.setObjectName("gbox_Mode")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbox_Mode)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cbox_RGB = QtWidgets.QCheckBox(self.gbox_Mode)
        self.cbox_RGB.setChecked(False)
        self.cbox_RGB.setObjectName("cbox_RGB")
        self.gridLayout_4.addWidget(self.cbox_RGB, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(73, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 1, 1, 1)
        self.cbox_HSV = QtWidgets.QCheckBox(self.gbox_Mode)
        self.cbox_HSV.setChecked(True)
        self.cbox_HSV.setObjectName("cbox_HSV")
        self.gridLayout_4.addWidget(self.cbox_HSV, 1, 0, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 106, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.gbox_Mode)
        self.result = QtWidgets.QWidget(self.splitter_2)
        self.result.setMinimumSize(QtCore.QSize(0, 150))
        self.result.setMaximumSize(QtCore.QSize(16777215, 400))
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionExtract = QtWidgets.QAction(MainWindow)
        self.actionExtract.setObjectName("actionExtract")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.menuFile.addAction(self.actionCreate)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionExtract)
        self.menuHelp.addAction(self.actionUpdate)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExport.triggered.connect(self.pbtn_Export.click)
        self.actionImport.triggered.connect(self.pbtn_Import.click)
        self.actionCreate.triggered.connect(self.pbtn_Create.click)
        self.actionExtract.triggered.connect(self.pbtn_Extract.click)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gbox_Rule.setTitle(_translate("MainWindow", "Rule"))
        self.rbtn_analogous.setText(_translate("MainWindow", "Analogous"))
        self.rbtn_monochromatic.setText(_translate("MainWindow", "Monochromatic"))
        self.rbtn_triad.setText(_translate("MainWindow", "Triad"))
        self.rbtn_tetrad.setText(_translate("MainWindow", "Tetrad"))
        self.rbtn_pentad.setText(_translate("MainWindow", "Pentad"))
        self.rbtn_complementary.setText(_translate("MainWindow", "Complementary"))
        self.rbtn_shades.setText(_translate("MainWindow", "Shades"))
        self.rbtn_custom.setText(_translate("MainWindow", "Custom"))
        self.gbox_View.setTitle(_translate("MainWindow", "View"))
        self.rbtn_individual.setText(_translate("MainWindow", "Individual"))
        self.rbtn_referential.setText(_translate("MainWindow", "Referential"))
        self.rbtn_overall.setText(_translate("MainWindow", "Overall"))
        self.gbox_Operation.setTitle(_translate("MainWindow", "Operation"))
        self.pbtn_Import.setText(_translate("MainWindow", "Import"))
        self.pbtn_Export.setText(_translate("MainWindow", "Export"))
        self.pbtn_Create.setText(_translate("MainWindow", "Create"))
        self.pbtn_Extract.setText(_translate("MainWindow", "Extract"))
        self.gbox_Mode.setTitle(_translate("MainWindow", "Mode"))
        self.cbox_RGB.setText(_translate("MainWindow", "RGB"))
        self.cbox_HSV.setText(_translate("MainWindow", "HSV"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionCreate.setText(_translate("MainWindow", "Create"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As ..."))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionExtract.setText(_translate("MainWindow", "Extract"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionUpdate.setText(_translate("MainWindow", "Update"))


