# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setting_dialog(object):
    def setupUi(self, setting_dialog):
        setting_dialog.setObjectName("setting_dialog")
        setting_dialog.resize(535, 640)
        setting_dialog.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(setting_dialog)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(setting_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.setti_items = QtWidgets.QTabWidget(setting_dialog)
        self.setti_items.setTabPosition(QtWidgets.QTabWidget.North)
        self.setti_items.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.setti_items.setDocumentMode(False)
        self.setti_items.setObjectName("setti_items")
        self.setti_interface = QtWidgets.QWidget()
        self.setti_interface.setObjectName("setti_interface")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.setti_interface)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.st_gbox_lang = QtWidgets.QGroupBox(self.setti_interface)
        self.st_gbox_lang.setMinimumSize(QtCore.QSize(0, 0))
        self.st_gbox_lang.setObjectName("st_gbox_lang")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.st_gbox_lang)
        self.gridLayout_7.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_7.setSpacing(8)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.st_label_lang = QtWidgets.QLabel(self.st_gbox_lang)
        self.st_label_lang.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_lang.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_lang.setObjectName("st_label_lang")
        self.gridLayout_7.addWidget(self.st_label_lang, 0, 0, 1, 1)
        self.st_cobox_21 = QtWidgets.QComboBox(self.st_gbox_lang)
        self.st_cobox_21.setMinimumSize(QtCore.QSize(200, 0))
        self.st_cobox_21.setObjectName("st_cobox_21")
        self.gridLayout_7.addWidget(self.st_cobox_21, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(322, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.st_gbox_lang)
        self.st_gbox_sqr_itf = QtWidgets.QGroupBox(self.setti_interface)
        self.st_gbox_sqr_itf.setObjectName("st_gbox_sqr_itf")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.st_gbox_sqr_itf)
        self.gridLayout_2.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_2.setSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(447, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.st_p_6 = QtWidgets.QDoubleSpinBox(self.st_gbox_sqr_itf)
        self.st_p_6.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_6.setMinimum(0.0)
        self.st_p_6.setMaximum(1.0)
        self.st_p_6.setSingleStep(0.1)
        self.st_p_6.setProperty("value", 0.9)
        self.st_p_6.setObjectName("st_p_6")
        self.gridLayout_2.addWidget(self.st_p_6, 0, 1, 1, 1)
        self.st_label_widratio = QtWidgets.QLabel(self.st_gbox_sqr_itf)
        self.st_label_widratio.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_widratio.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_widratio.setObjectName("st_label_widratio")
        self.gridLayout_2.addWidget(self.st_label_widratio, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.st_gbox_sqr_itf)
        self.st_gbox_whl_itf = QtWidgets.QGroupBox(self.setti_interface)
        self.st_gbox_whl_itf.setObjectName("st_gbox_whl_itf")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.st_gbox_whl_itf)
        self.gridLayout_3.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_3.setSpacing(8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.st_p_4 = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_itf)
        self.st_p_4.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_4.setMinimum(0.0)
        self.st_p_4.setMaximum(1.0)
        self.st_p_4.setSingleStep(0.01)
        self.st_p_4.setProperty("value", 0.05)
        self.st_p_4.setObjectName("st_p_4")
        self.gridLayout_3.addWidget(self.st_p_4, 1, 1, 1, 1)
        self.st_p_3 = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_itf)
        self.st_p_3.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_3.setMinimum(0.0)
        self.st_p_3.setMaximum(1.0)
        self.st_p_3.setSingleStep(0.1)
        self.st_p_3.setProperty("value", 0.8)
        self.st_p_3.setObjectName("st_p_3")
        self.gridLayout_3.addWidget(self.st_p_3, 0, 1, 1, 1)
        self.st_sp_13_r = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_13_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_13_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_13_r.setMaximum(255)
        self.st_sp_13_r.setProperty("value", 200)
        self.st_sp_13_r.setObjectName("st_sp_13_r")
        self.gridLayout_3.addWidget(self.st_sp_13_r, 4, 1, 1, 1)
        self.st_label_vb_color = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_vb_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_vb_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_vb_color.setObjectName("st_label_vb_color")
        self.gridLayout_3.addWidget(self.st_label_vb_color, 5, 0, 1, 1)
        self.st_label_ia_color = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_ia_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_ia_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_ia_color.setObjectName("st_label_ia_color")
        self.gridLayout_3.addWidget(self.st_label_ia_color, 4, 0, 1, 1)
        self.st_sp_12_b = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_12_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_12_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_12_b.setMaximum(255)
        self.st_sp_12_b.setObjectName("st_sp_12_b")
        self.gridLayout_3.addWidget(self.st_sp_12_b, 3, 3, 1, 1)
        self.st_label_raduis = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_raduis.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_raduis.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_raduis.setObjectName("st_label_raduis")
        self.gridLayout_3.addWidget(self.st_label_raduis, 0, 0, 1, 1)
        self.st_sp_12_r = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_12_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_12_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_12_r.setMaximum(255)
        self.st_sp_12_r.setObjectName("st_sp_12_r")
        self.gridLayout_3.addWidget(self.st_sp_12_r, 3, 1, 1, 1)
        self.st_sp_13_b = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_13_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_13_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_13_b.setMaximum(255)
        self.st_sp_13_b.setProperty("value", 200)
        self.st_sp_13_b.setObjectName("st_sp_13_b")
        self.gridLayout_3.addWidget(self.st_sp_13_b, 4, 3, 1, 1)
        self.st_label_at_color = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_at_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_at_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_at_color.setObjectName("st_label_at_color")
        self.gridLayout_3.addWidget(self.st_label_at_color, 3, 0, 1, 1)
        self.st_sp_13_g = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_13_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_13_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_13_g.setMaximum(255)
        self.st_sp_13_g.setProperty("value", 200)
        self.st_sp_13_g.setObjectName("st_sp_13_g")
        self.gridLayout_3.addWidget(self.st_sp_13_g, 4, 2, 1, 1)
        self.st_sp_14_r = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_14_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_14_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_14_r.setMaximum(255)
        self.st_sp_14_r.setProperty("value", 230)
        self.st_sp_14_r.setObjectName("st_sp_14_r")
        self.gridLayout_3.addWidget(self.st_sp_14_r, 5, 1, 1, 1)
        self.st_label_color_radius = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_color_radius.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_color_radius.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_color_radius.setObjectName("st_label_color_radius")
        self.gridLayout_3.addWidget(self.st_label_color_radius, 1, 0, 1, 1)
        self.st_p_7 = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_itf)
        self.st_p_7.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_7.setMinimum(0.0)
        self.st_p_7.setMaximum(1.0)
        self.st_p_7.setSingleStep(0.1)
        self.st_p_7.setProperty("value", 0.8)
        self.st_p_7.setObjectName("st_p_7")
        self.gridLayout_3.addWidget(self.st_p_7, 2, 1, 1, 1)
        self.st_label_bar_widratio = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_bar_widratio.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_bar_widratio.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_bar_widratio.setObjectName("st_label_bar_widratio")
        self.gridLayout_3.addWidget(self.st_label_bar_widratio, 2, 0, 1, 1)
        self.st_sp_12_g = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_12_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_12_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_12_g.setMaximum(255)
        self.st_sp_12_g.setObjectName("st_sp_12_g")
        self.gridLayout_3.addWidget(self.st_sp_12_g, 3, 2, 1, 1)
        self.st_sp_14_g = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_14_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_14_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_14_g.setMaximum(255)
        self.st_sp_14_g.setProperty("value", 230)
        self.st_sp_14_g.setObjectName("st_sp_14_g")
        self.gridLayout_3.addWidget(self.st_sp_14_g, 5, 2, 1, 1)
        self.st_sp_14_b = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_14_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_14_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_14_b.setMaximum(255)
        self.st_sp_14_b.setProperty("value", 230)
        self.st_sp_14_b.setObjectName("st_sp_14_b")
        self.gridLayout_3.addWidget(self.st_sp_14_b, 5, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(325, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 5, 4, 1, 1)
        self.verticalLayout.addWidget(self.st_gbox_whl_itf)
        self.st_gbox_img_itf = QtWidgets.QGroupBox(self.setti_interface)
        self.st_gbox_img_itf.setObjectName("st_gbox_img_itf")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.st_gbox_img_itf)
        self.gridLayout_4.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_4.setSpacing(8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.st_label_half_sp = QtWidgets.QLabel(self.st_gbox_img_itf)
        self.st_label_half_sp.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_half_sp.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_half_sp.setObjectName("st_label_half_sp")
        self.gridLayout_4.addWidget(self.st_label_half_sp, 1, 0, 1, 1)
        self.st_p_5 = QtWidgets.QDoubleSpinBox(self.st_gbox_img_itf)
        self.st_p_5.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_5.setSuffix("")
        self.st_p_5.setMinimum(0.0)
        self.st_p_5.setMaximum(1.0)
        self.st_p_5.setSingleStep(0.01)
        self.st_p_5.setProperty("value", 0.1)
        self.st_p_5.setObjectName("st_p_5")
        self.gridLayout_4.addWidget(self.st_p_5, 0, 1, 1, 1)
        self.st_p_11 = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_p_11.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_11.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_11.setMinimum(1)
        self.st_p_11.setMaximum(200)
        self.st_p_11.setProperty("value", 5)
        self.st_p_11.setObjectName("st_p_11")
        self.gridLayout_4.addWidget(self.st_p_11, 1, 1, 1, 1)
        self.st_label_5 = QtWidgets.QLabel(self.st_gbox_img_itf)
        self.st_label_5.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_5.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_5.setObjectName("st_label_5")
        self.gridLayout_4.addWidget(self.st_label_5, 0, 0, 1, 1)
        self.st_sp_15_r = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_15_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_15_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_15_r.setMaximum(255)
        self.st_sp_15_r.setProperty("value", 100)
        self.st_sp_15_r.setObjectName("st_sp_15_r")
        self.gridLayout_4.addWidget(self.st_sp_15_r, 2, 1, 1, 1)
        self.st_sp_15_g = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_15_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_15_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_15_g.setMaximum(255)
        self.st_sp_15_g.setProperty("value", 100)
        self.st_sp_15_g.setObjectName("st_sp_15_g")
        self.gridLayout_4.addWidget(self.st_sp_15_g, 2, 2, 1, 1)
        self.st_sp_15_b = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_15_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_15_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_15_b.setMaximum(255)
        self.st_sp_15_b.setProperty("value", 100)
        self.st_sp_15_b.setObjectName("st_sp_15_b")
        self.gridLayout_4.addWidget(self.st_sp_15_b, 2, 3, 1, 1)
        self.st_label_vs_color = QtWidgets.QLabel(self.st_gbox_img_itf)
        self.st_label_vs_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_vs_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_vs_color.setObjectName("st_label_vs_color")
        self.gridLayout_4.addWidget(self.st_label_vs_color, 2, 0, 1, 1)
        self.st_sp_16_g = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_16_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_16_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_16_g.setMaximum(255)
        self.st_sp_16_g.setProperty("value", 100)
        self.st_sp_16_g.setObjectName("st_sp_16_g")
        self.gridLayout_4.addWidget(self.st_sp_16_g, 3, 2, 1, 1)
        self.st_label_it_color = QtWidgets.QLabel(self.st_gbox_img_itf)
        self.st_label_it_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_it_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_it_color.setObjectName("st_label_it_color")
        self.gridLayout_4.addWidget(self.st_label_it_color, 4, 0, 1, 1)
        self.st_sp_17_g = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_17_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_17_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_17_g.setMaximum(255)
        self.st_sp_17_g.setProperty("value", 200)
        self.st_sp_17_g.setObjectName("st_sp_17_g")
        self.gridLayout_4.addWidget(self.st_sp_17_g, 4, 2, 1, 1)
        self.st_label_st_color = QtWidgets.QLabel(self.st_gbox_img_itf)
        self.st_label_st_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_st_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_st_color.setObjectName("st_label_st_color")
        self.gridLayout_4.addWidget(self.st_label_st_color, 3, 0, 1, 1)
        self.st_sp_17_b = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_17_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_17_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_17_b.setMaximum(255)
        self.st_sp_17_b.setProperty("value", 200)
        self.st_sp_17_b.setObjectName("st_sp_17_b")
        self.gridLayout_4.addWidget(self.st_sp_17_b, 4, 3, 1, 1)
        self.st_sp_16_r = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_16_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_16_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_16_r.setMaximum(255)
        self.st_sp_16_r.setProperty("value", 100)
        self.st_sp_16_r.setObjectName("st_sp_16_r")
        self.gridLayout_4.addWidget(self.st_sp_16_r, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(333, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 4, 4, 1, 1)
        self.st_sp_17_r = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_17_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_17_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_17_r.setMaximum(255)
        self.st_sp_17_r.setProperty("value", 200)
        self.st_sp_17_r.setObjectName("st_sp_17_r")
        self.gridLayout_4.addWidget(self.st_sp_17_r, 4, 1, 1, 1)
        self.st_sp_16_b = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_16_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_16_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_16_b.setMaximum(255)
        self.st_sp_16_b.setProperty("value", 100)
        self.st_sp_16_b.setObjectName("st_sp_16_b")
        self.gridLayout_4.addWidget(self.st_sp_16_b, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.st_gbox_img_itf)
        self.setti_items.addTab(self.setti_interface, "")
        self.setti_rule = QtWidgets.QWidget()
        self.setti_rule.setObjectName("setti_rule")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.setti_rule)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.st_gbox_whl_rule = QtWidgets.QGroupBox(self.setti_rule)
        self.st_gbox_whl_rule.setObjectName("st_gbox_whl_rule")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.st_gbox_whl_rule)
        self.gridLayout_6.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_6.setSpacing(8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.st_label_h_range_from = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_h_range_from.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_h_range_from.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_h_range_from.setObjectName("st_label_h_range_from")
        self.gridLayout_6.addWidget(self.st_label_h_range_from, 0, 0, 1, 1)
        self.st_dp_0_from = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_0_from.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_0_from.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_0_from.setMaximum(360.0)
        self.st_dp_0_from.setSingleStep(10.0)
        self.st_dp_0_from.setObjectName("st_dp_0_from")
        self.gridLayout_6.addWidget(self.st_dp_0_from, 0, 1, 1, 1)
        self.st_label_h_range_to = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_h_range_to.setMinimumSize(QtCore.QSize(30, 20))
        self.st_label_h_range_to.setMaximumSize(QtCore.QSize(30, 20))
        self.st_label_h_range_to.setObjectName("st_label_h_range_to")
        self.gridLayout_6.addWidget(self.st_label_h_range_to, 0, 2, 1, 1)
        self.st_dp_0_to = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_0_to.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_0_to.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_0_to.setMaximum(360.0)
        self.st_dp_0_to.setSingleStep(10.0)
        self.st_dp_0_to.setProperty("value", 360.0)
        self.st_dp_0_to.setObjectName("st_dp_0_to")
        self.gridLayout_6.addWidget(self.st_dp_0_to, 0, 3, 1, 1)
        self.st_label_s_range_from = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_s_range_from.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_s_range_from.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_s_range_from.setObjectName("st_label_s_range_from")
        self.gridLayout_6.addWidget(self.st_label_s_range_from, 1, 0, 1, 1)
        self.st_dp_1_from = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_1_from.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_1_from.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_1_from.setMaximum(1.0)
        self.st_dp_1_from.setSingleStep(0.1)
        self.st_dp_1_from.setObjectName("st_dp_1_from")
        self.gridLayout_6.addWidget(self.st_dp_1_from, 1, 1, 1, 1)
        self.st_label_s_range_to = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_s_range_to.setMinimumSize(QtCore.QSize(30, 20))
        self.st_label_s_range_to.setMaximumSize(QtCore.QSize(30, 20))
        self.st_label_s_range_to.setObjectName("st_label_s_range_to")
        self.gridLayout_6.addWidget(self.st_label_s_range_to, 1, 2, 1, 1)
        self.st_dp_1_to = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_1_to.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_1_to.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_1_to.setMaximum(1.0)
        self.st_dp_1_to.setSingleStep(0.1)
        self.st_dp_1_to.setProperty("value", 1.0)
        self.st_dp_1_to.setObjectName("st_dp_1_to")
        self.gridLayout_6.addWidget(self.st_dp_1_to, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(294, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 4, 1, 1)
        self.st_label_v_range_from = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_v_range_from.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_v_range_from.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_v_range_from.setObjectName("st_label_v_range_from")
        self.gridLayout_6.addWidget(self.st_label_v_range_from, 2, 0, 1, 1)
        self.st_dp_2_from = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_2_from.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_2_from.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_2_from.setMaximum(1.0)
        self.st_dp_2_from.setSingleStep(0.1)
        self.st_dp_2_from.setObjectName("st_dp_2_from")
        self.gridLayout_6.addWidget(self.st_dp_2_from, 2, 1, 1, 1)
        self.st_label_v_range_to = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_v_range_to.setMinimumSize(QtCore.QSize(30, 20))
        self.st_label_v_range_to.setMaximumSize(QtCore.QSize(30, 20))
        self.st_label_v_range_to.setObjectName("st_label_v_range_to")
        self.gridLayout_6.addWidget(self.st_label_v_range_to, 2, 2, 1, 1)
        self.st_dp_2_to = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_2_to.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_2_to.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_2_to.setMaximum(1.0)
        self.st_dp_2_to.setSingleStep(0.1)
        self.st_dp_2_to.setProperty("value", 1.0)
        self.st_dp_2_to.setObjectName("st_dp_2_to")
        self.gridLayout_6.addWidget(self.st_dp_2_to, 2, 3, 1, 1)
        self.st_label_hm_rule = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_hm_rule.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_hm_rule.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_hm_rule.setObjectName("st_label_hm_rule")
        self.gridLayout_6.addWidget(self.st_label_hm_rule, 3, 0, 1, 1)
        self.st_comb_20 = QtWidgets.QComboBox(self.st_gbox_whl_rule)
        self.st_comb_20.setMinimumSize(QtCore.QSize(120, 22))
        self.st_comb_20.setMaximumSize(QtCore.QSize(120, 22))
        self.st_comb_20.setObjectName("st_comb_20")
        self.st_comb_20.addItem("")
        self.st_comb_20.addItem("")
        self.st_comb_20.addItem("")
        self.st_comb_20.addItem("")
        self.st_comb_20.addItem("")
        self.st_comb_20.addItem("")
        self.st_comb_20.addItem("")
        self.st_comb_20.addItem("")
        self.gridLayout_6.addWidget(self.st_comb_20, 3, 1, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 4, 0, 1, 1)
        self.st_cbox_22 = QtWidgets.QCheckBox(self.st_gbox_whl_rule)
        self.st_cbox_22.setMinimumSize(QtCore.QSize(300, 22))
        self.st_cbox_22.setMaximumSize(QtCore.QSize(300, 22))
        self.st_cbox_22.setChecked(True)
        self.st_cbox_22.setObjectName("st_cbox_22")
        self.gridLayout_6.addWidget(self.st_cbox_22, 5, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 6, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.st_gbox_whl_rule)
        self.st_gbox_img_rule = QtWidgets.QGroupBox(self.setti_rule)
        self.st_gbox_img_rule.setObjectName("st_gbox_img_rule")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.st_gbox_img_rule)
        self.gridLayout_5.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_5.setSpacing(8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.st_label_graph_types = QtWidgets.QLabel(self.st_gbox_img_rule)
        self.st_label_graph_types.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_graph_types.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_graph_types.setObjectName("st_label_graph_types")
        self.gridLayout_5.addWidget(self.st_label_graph_types, 0, 0, 1, 1)
        self.st_cobox_18_0 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_18_0.setMinimumSize(QtCore.QSize(120, 22))
        self.st_cobox_18_0.setMaximumSize(QtCore.QSize(120, 22))
        self.st_cobox_18_0.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.st_cobox_18_0.setObjectName("st_cobox_18_0")
        self.st_cobox_18_0.addItem("")
        self.st_cobox_18_0.addItem("")
        self.st_cobox_18_0.addItem("")
        self.st_cobox_18_0.addItem("")
        self.st_cobox_18_0.addItem("")
        self.st_cobox_18_0.addItem("")
        self.st_cobox_18_0.addItem("")
        self.st_cobox_18_0.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_18_0, 0, 1, 1, 1)
        self.st_cobox_18_1 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_18_1.setMinimumSize(QtCore.QSize(120, 22))
        self.st_cobox_18_1.setMaximumSize(QtCore.QSize(120, 22))
        self.st_cobox_18_1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.st_cobox_18_1.setObjectName("st_cobox_18_1")
        self.st_cobox_18_1.addItem("")
        self.st_cobox_18_1.addItem("")
        self.st_cobox_18_1.addItem("")
        self.st_cobox_18_1.addItem("")
        self.st_cobox_18_1.addItem("")
        self.st_cobox_18_1.addItem("")
        self.st_cobox_18_1.addItem("")
        self.st_cobox_18_1.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_18_1, 0, 2, 1, 1)
        self.st_cobox_18_2 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_18_2.setMinimumSize(QtCore.QSize(120, 22))
        self.st_cobox_18_2.setMaximumSize(QtCore.QSize(120, 22))
        self.st_cobox_18_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.st_cobox_18_2.setObjectName("st_cobox_18_2")
        self.st_cobox_18_2.addItem("")
        self.st_cobox_18_2.addItem("")
        self.st_cobox_18_2.addItem("")
        self.st_cobox_18_2.addItem("")
        self.st_cobox_18_2.addItem("")
        self.st_cobox_18_2.addItem("")
        self.st_cobox_18_2.addItem("")
        self.st_cobox_18_2.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_18_2, 1, 1, 1, 1)
        self.st_cobox_18_3 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_18_3.setMinimumSize(QtCore.QSize(120, 22))
        self.st_cobox_18_3.setMaximumSize(QtCore.QSize(120, 22))
        self.st_cobox_18_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.st_cobox_18_3.setObjectName("st_cobox_18_3")
        self.st_cobox_18_3.addItem("")
        self.st_cobox_18_3.addItem("")
        self.st_cobox_18_3.addItem("")
        self.st_cobox_18_3.addItem("")
        self.st_cobox_18_3.addItem("")
        self.st_cobox_18_3.addItem("")
        self.st_cobox_18_3.addItem("")
        self.st_cobox_18_3.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_18_3, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 1, 3, 1, 1)
        self.st_label_graph_chls = QtWidgets.QLabel(self.st_gbox_img_rule)
        self.st_label_graph_chls.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_graph_chls.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_graph_chls.setObjectName("st_label_graph_chls")
        self.gridLayout_5.addWidget(self.st_label_graph_chls, 2, 0, 1, 1)
        self.st_cobox_19_0 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_19_0.setMinimumSize(QtCore.QSize(80, 22))
        self.st_cobox_19_0.setMaximumSize(QtCore.QSize(80, 22))
        self.st_cobox_19_0.setObjectName("st_cobox_19_0")
        self.st_cobox_19_0.addItem("")
        self.st_cobox_19_0.addItem("")
        self.st_cobox_19_0.addItem("")
        self.st_cobox_19_0.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_19_0, 2, 1, 1, 1)
        self.st_cobox_19_1 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_19_1.setMinimumSize(QtCore.QSize(80, 22))
        self.st_cobox_19_1.setMaximumSize(QtCore.QSize(80, 22))
        self.st_cobox_19_1.setObjectName("st_cobox_19_1")
        self.st_cobox_19_1.addItem("")
        self.st_cobox_19_1.addItem("")
        self.st_cobox_19_1.addItem("")
        self.st_cobox_19_1.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_19_1, 2, 2, 1, 1)
        self.st_cobox_19_2 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_19_2.setMinimumSize(QtCore.QSize(80, 22))
        self.st_cobox_19_2.setMaximumSize(QtCore.QSize(80, 22))
        self.st_cobox_19_2.setObjectName("st_cobox_19_2")
        self.st_cobox_19_2.addItem("")
        self.st_cobox_19_2.addItem("")
        self.st_cobox_19_2.addItem("")
        self.st_cobox_19_2.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_19_2, 3, 1, 1, 1)
        self.st_cobox_19_3 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_19_3.setMinimumSize(QtCore.QSize(80, 22))
        self.st_cobox_19_3.setMaximumSize(QtCore.QSize(80, 22))
        self.st_cobox_19_3.setObjectName("st_cobox_19_3")
        self.st_cobox_19_3.addItem("")
        self.st_cobox_19_3.addItem("")
        self.st_cobox_19_3.addItem("")
        self.st_cobox_19_3.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_19_3, 3, 2, 1, 1)
        self.st_label_zoom_step = QtWidgets.QLabel(self.st_gbox_img_rule)
        self.st_label_zoom_step.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_zoom_step.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_zoom_step.setObjectName("st_label_zoom_step")
        self.gridLayout_5.addWidget(self.st_label_zoom_step, 4, 0, 1, 1)
        self.st_p_8 = QtWidgets.QDoubleSpinBox(self.st_gbox_img_rule)
        self.st_p_8.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_8.setMinimum(1.0)
        self.st_p_8.setMaximum(10.0)
        self.st_p_8.setSingleStep(0.05)
        self.st_p_8.setProperty("value", 1.3)
        self.st_p_8.setObjectName("st_p_8")
        self.gridLayout_5.addWidget(self.st_p_8, 4, 1, 1, 1)
        self.st_label_move_step = QtWidgets.QLabel(self.st_gbox_img_rule)
        self.st_label_move_step.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_move_step.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_move_step.setObjectName("st_label_move_step")
        self.gridLayout_5.addWidget(self.st_label_move_step, 5, 0, 1, 1)
        self.st_p_9 = QtWidgets.QSpinBox(self.st_gbox_img_rule)
        self.st_p_9.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_9.setMinimum(0)
        self.st_p_9.setMaximum(500)
        self.st_p_9.setProperty("value", 5)
        self.st_p_9.setObjectName("st_p_9")
        self.gridLayout_5.addWidget(self.st_p_9, 5, 1, 1, 1)
        self.st_label_select_dist = QtWidgets.QLabel(self.st_gbox_img_rule)
        self.st_label_select_dist.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_select_dist.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_select_dist.setObjectName("st_label_select_dist")
        self.gridLayout_5.addWidget(self.st_label_select_dist, 6, 0, 1, 1)
        self.st_p_10 = QtWidgets.QSpinBox(self.st_gbox_img_rule)
        self.st_p_10.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_10.setMinimum(1)
        self.st_p_10.setMaximum(500)
        self.st_p_10.setProperty("value", 10)
        self.st_p_10.setObjectName("st_p_10")
        self.gridLayout_5.addWidget(self.st_p_10, 6, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 7, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.st_gbox_img_rule)
        self.setti_items.addTab(self.setti_rule, "")
        self.gridLayout.addWidget(self.setti_items, 0, 0, 1, 1)

        self.retranslateUi(setting_dialog)
        self.setti_items.setCurrentIndex(0)
        self.st_cobox_18_1.setCurrentIndex(7)
        self.st_cobox_18_2.setCurrentIndex(7)
        self.st_cobox_18_3.setCurrentIndex(7)
        self.st_cobox_19_1.setCurrentIndex(1)
        self.st_cobox_19_2.setCurrentIndex(2)
        self.st_cobox_19_3.setCurrentIndex(3)
        self.buttonBox.accepted.connect(setting_dialog.accept)
        self.buttonBox.rejected.connect(setting_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(setting_dialog)

    def retranslateUi(self, setting_dialog):
        _translate = QtCore.QCoreApplication.translate
        self.st_gbox_lang.setTitle(_translate("setting_dialog", "Work space"))
        self.st_label_lang.setText(_translate("setting_dialog", "Language"))
        self.st_gbox_sqr_itf.setTitle(_translate("setting_dialog", "Color Square"))
        self.st_label_widratio.setText(_translate("setting_dialog", "Color square length"))
        self.st_gbox_whl_itf.setTitle(_translate("setting_dialog", "Color wheel"))
        self.st_label_vb_color.setText(_translate("setting_dialog", "Bar edge color"))
        self.st_label_ia_color.setText(_translate("setting_dialog", "Inactivated tag color"))
        self.st_label_raduis.setText(_translate("setting_dialog", "Color wheel radius"))
        self.st_label_at_color.setText(_translate("setting_dialog", "Activated tag color"))
        self.st_label_color_radius.setText(_translate("setting_dialog", "Color tag radius"))
        self.st_label_bar_widratio.setText(_translate("setting_dialog", "Color bar length"))
        self.st_gbox_img_itf.setTitle(_translate("setting_dialog", "Graph view"))
        self.st_label_half_sp.setText(_translate("setting_dialog", "Layer separation width"))
        self.st_label_5.setText(_translate("setting_dialog", "Drag hint radius"))
        self.st_label_vs_color.setText(_translate("setting_dialog", "Drag hint color"))
        self.st_label_it_color.setText(_translate("setting_dialog", "Reference point color"))
        self.st_label_st_color.setText(_translate("setting_dialog", "Selection point color"))
        self.setti_items.setTabText(self.setti_items.indexOf(self.setti_interface), _translate("setting_dialog", "Interface"))
        self.st_gbox_whl_rule.setTitle(_translate("setting_dialog", "Color wheel"))
        self.st_label_h_range_from.setText(_translate("setting_dialog", "H range from"))
        self.st_label_h_range_to.setText(_translate("setting_dialog", "to"))
        self.st_label_s_range_from.setText(_translate("setting_dialog", "S range from"))
        self.st_label_s_range_to.setText(_translate("setting_dialog", "to"))
        self.st_label_v_range_from.setText(_translate("setting_dialog", "V range from"))
        self.st_label_v_range_to.setText(_translate("setting_dialog", "to"))
        self.st_label_hm_rule.setText(_translate("setting_dialog", "Harmony rule"))
        self.st_comb_20.setItemText(0, _translate("setting_dialog", "Analogous"))
        self.st_comb_20.setItemText(1, _translate("setting_dialog", "Monochromatic"))
        self.st_comb_20.setItemText(2, _translate("setting_dialog", "Triad"))
        self.st_comb_20.setItemText(3, _translate("setting_dialog", "Tetrad"))
        self.st_comb_20.setItemText(4, _translate("setting_dialog", "Pentad"))
        self.st_comb_20.setItemText(5, _translate("setting_dialog", "Complementary"))
        self.st_comb_20.setItemText(6, _translate("setting_dialog", "Shades"))
        self.st_comb_20.setItemText(7, _translate("setting_dialog", "Custom"))
        self.st_cbox_22.setText(_translate("setting_dialog", "Press and select instantly"))
        self.st_gbox_img_rule.setTitle(_translate("setting_dialog", "Graph view"))
        self.st_label_graph_types.setText(_translate("setting_dialog", "Graph types"))
        self.st_cobox_18_0.setItemText(0, _translate("setting_dialog", "RGB-Normal"))
        self.st_cobox_18_0.setItemText(1, _translate("setting_dialog", "RGB-Vertical"))
        self.st_cobox_18_0.setItemText(2, _translate("setting_dialog", "RGB-Horizontal"))
        self.st_cobox_18_0.setItemText(3, _translate("setting_dialog", "RGB-Final"))
        self.st_cobox_18_0.setItemText(4, _translate("setting_dialog", "HSV-Normal"))
        self.st_cobox_18_0.setItemText(5, _translate("setting_dialog", "HSV-Vertical"))
        self.st_cobox_18_0.setItemText(6, _translate("setting_dialog", "HSV-Horizontal"))
        self.st_cobox_18_0.setItemText(7, _translate("setting_dialog", "HSV-Final"))
        self.st_cobox_18_1.setItemText(0, _translate("setting_dialog", "RGB-Normal"))
        self.st_cobox_18_1.setItemText(1, _translate("setting_dialog", "RGB-Vertical"))
        self.st_cobox_18_1.setItemText(2, _translate("setting_dialog", "RGB-Horizontal"))
        self.st_cobox_18_1.setItemText(3, _translate("setting_dialog", "RGB-Final"))
        self.st_cobox_18_1.setItemText(4, _translate("setting_dialog", "HSV-Normal"))
        self.st_cobox_18_1.setItemText(5, _translate("setting_dialog", "HSV-Vertical"))
        self.st_cobox_18_1.setItemText(6, _translate("setting_dialog", "HSV-Horizontal"))
        self.st_cobox_18_1.setItemText(7, _translate("setting_dialog", "HSV-Final"))
        self.st_cobox_18_2.setItemText(0, _translate("setting_dialog", "RGB-Normal"))
        self.st_cobox_18_2.setItemText(1, _translate("setting_dialog", "RGB-Vertical"))
        self.st_cobox_18_2.setItemText(2, _translate("setting_dialog", "RGB-Horizontal"))
        self.st_cobox_18_2.setItemText(3, _translate("setting_dialog", "RGB-Final"))
        self.st_cobox_18_2.setItemText(4, _translate("setting_dialog", "HSV-Normal"))
        self.st_cobox_18_2.setItemText(5, _translate("setting_dialog", "HSV-Vertical"))
        self.st_cobox_18_2.setItemText(6, _translate("setting_dialog", "HSV-Horizontal"))
        self.st_cobox_18_2.setItemText(7, _translate("setting_dialog", "HSV-Final"))
        self.st_cobox_18_3.setItemText(0, _translate("setting_dialog", "RGB-Normal"))
        self.st_cobox_18_3.setItemText(1, _translate("setting_dialog", "RGB-Vertical"))
        self.st_cobox_18_3.setItemText(2, _translate("setting_dialog", "RGB-Horizontal"))
        self.st_cobox_18_3.setItemText(3, _translate("setting_dialog", "RGB-Final"))
        self.st_cobox_18_3.setItemText(4, _translate("setting_dialog", "HSV-Normal"))
        self.st_cobox_18_3.setItemText(5, _translate("setting_dialog", "HSV-Vertical"))
        self.st_cobox_18_3.setItemText(6, _translate("setting_dialog", "HSV-Horizontal"))
        self.st_cobox_18_3.setItemText(7, _translate("setting_dialog", "HSV-Final"))
        self.st_label_graph_chls.setText(_translate("setting_dialog", "Graph channels"))
        self.st_cobox_19_0.setItemText(0, _translate("setting_dialog", "All"))
        self.st_cobox_19_0.setItemText(1, _translate("setting_dialog", "1 R/H"))
        self.st_cobox_19_0.setItemText(2, _translate("setting_dialog", "2 G/S"))
        self.st_cobox_19_0.setItemText(3, _translate("setting_dialog", "3 B/V"))
        self.st_cobox_19_1.setItemText(0, _translate("setting_dialog", "All"))
        self.st_cobox_19_1.setItemText(1, _translate("setting_dialog", "1 R/H"))
        self.st_cobox_19_1.setItemText(2, _translate("setting_dialog", "2 G/S"))
        self.st_cobox_19_1.setItemText(3, _translate("setting_dialog", "3 B/V"))
        self.st_cobox_19_2.setItemText(0, _translate("setting_dialog", "All"))
        self.st_cobox_19_2.setItemText(1, _translate("setting_dialog", "1 R/H"))
        self.st_cobox_19_2.setItemText(2, _translate("setting_dialog", "2 G/S"))
        self.st_cobox_19_2.setItemText(3, _translate("setting_dialog", "3 B/V"))
        self.st_cobox_19_3.setItemText(0, _translate("setting_dialog", "All"))
        self.st_cobox_19_3.setItemText(1, _translate("setting_dialog", "1 R/H"))
        self.st_cobox_19_3.setItemText(2, _translate("setting_dialog", "2 G/S"))
        self.st_cobox_19_3.setItemText(3, _translate("setting_dialog", "3 B/V"))
        self.st_label_zoom_step.setText(_translate("setting_dialog", "Zoom ratio per step"))
        self.st_label_move_step.setText(_translate("setting_dialog", "Move distance per step"))
        self.st_label_select_dist.setText(_translate("setting_dialog", "Selection scope"))
        self.setti_items.setTabText(self.setti_items.indexOf(self.setti_rule), _translate("setting_dialog", "Rule"))


