# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(535, 640)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.setti_items = QtWidgets.QTabWidget(Dialog)
        self.setti_items.setTabPosition(QtWidgets.QTabWidget.North)
        self.setti_items.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.setti_items.setDocumentMode(False)
        self.setti_items.setObjectName("setti_items")
        self.setti_interface = QtWidgets.QWidget()
        self.setti_interface.setObjectName("setti_interface")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.setti_interface)
        self.verticalLayout.setObjectName("verticalLayout")
        self.st_gbox_sqr_itf = QtWidgets.QGroupBox(self.setti_interface)
        self.st_gbox_sqr_itf.setObjectName("st_gbox_sqr_itf")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.st_gbox_sqr_itf)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.st_label_widratio = QtWidgets.QLabel(self.st_gbox_sqr_itf)
        self.st_label_widratio.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_widratio.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_widratio.setObjectName("st_label_widratio")
        self.gridLayout_2.addWidget(self.st_label_widratio, 0, 0, 1, 1)
        self.st_p_widratio = QtWidgets.QDoubleSpinBox(self.st_gbox_sqr_itf)
        self.st_p_widratio.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_widratio.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_widratio.setMinimum(0.4)
        self.st_p_widratio.setMaximum(1.0)
        self.st_p_widratio.setSingleStep(0.1)
        self.st_p_widratio.setProperty("value", 0.9)
        self.st_p_widratio.setObjectName("st_p_widratio")
        self.gridLayout_2.addWidget(self.st_p_widratio, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(447, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.st_gbox_sqr_itf)
        self.st_gbox_whl_itf = QtWidgets.QGroupBox(self.setti_interface)
        self.st_gbox_whl_itf.setObjectName("st_gbox_whl_itf")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.st_gbox_whl_itf)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.st_label_raduis = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_raduis.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_raduis.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_raduis.setObjectName("st_label_raduis")
        self.gridLayout_3.addWidget(self.st_label_raduis, 0, 0, 1, 1)
        self.st_p_radius = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_itf)
        self.st_p_radius.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_radius.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_radius.setMinimum(0.3)
        self.st_p_radius.setMaximum(0.9)
        self.st_p_radius.setSingleStep(0.1)
        self.st_p_radius.setProperty("value", 0.8)
        self.st_p_radius.setObjectName("st_p_radius")
        self.gridLayout_3.addWidget(self.st_p_radius, 0, 1, 1, 1)
        self.st_label_color_radius = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_color_radius.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_color_radius.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_color_radius.setObjectName("st_label_color_radius")
        self.gridLayout_3.addWidget(self.st_label_color_radius, 1, 0, 1, 1)
        self.st_p_color_radius = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_itf)
        self.st_p_color_radius.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_color_radius.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_color_radius.setMinimum(0.01)
        self.st_p_color_radius.setMaximum(0.2)
        self.st_p_color_radius.setSingleStep(0.01)
        self.st_p_color_radius.setProperty("value", 0.05)
        self.st_p_color_radius.setObjectName("st_p_color_radius")
        self.gridLayout_3.addWidget(self.st_p_color_radius, 1, 1, 1, 1)
        self.st_label_bar_widratio = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_bar_widratio.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_bar_widratio.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_bar_widratio.setObjectName("st_label_bar_widratio")
        self.gridLayout_3.addWidget(self.st_label_bar_widratio, 2, 0, 1, 1)
        self.st_p_bar_widratio = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_itf)
        self.st_p_bar_widratio.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_bar_widratio.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_bar_widratio.setMinimum(0.3)
        self.st_p_bar_widratio.setMaximum(0.9)
        self.st_p_bar_widratio.setSingleStep(0.1)
        self.st_p_bar_widratio.setProperty("value", 0.8)
        self.st_p_bar_widratio.setObjectName("st_p_bar_widratio")
        self.gridLayout_3.addWidget(self.st_p_bar_widratio, 2, 1, 1, 1)
        self.st_label_at_color = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_at_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_at_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_at_color.setObjectName("st_label_at_color")
        self.gridLayout_3.addWidget(self.st_label_at_color, 3, 0, 1, 1)
        self.st_sp_at_color_r = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_at_color_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_at_color_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_at_color_r.setMaximum(255)
        self.st_sp_at_color_r.setObjectName("st_sp_at_color_r")
        self.gridLayout_3.addWidget(self.st_sp_at_color_r, 3, 1, 1, 1)
        self.st_sp_at_color_g = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_at_color_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_at_color_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_at_color_g.setMaximum(255)
        self.st_sp_at_color_g.setObjectName("st_sp_at_color_g")
        self.gridLayout_3.addWidget(self.st_sp_at_color_g, 3, 2, 1, 1)
        self.st_sp_at_color_b = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_at_color_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_at_color_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_at_color_b.setMaximum(255)
        self.st_sp_at_color_b.setObjectName("st_sp_at_color_b")
        self.gridLayout_3.addWidget(self.st_sp_at_color_b, 3, 3, 1, 1)
        self.st_label_ia_color = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_ia_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_ia_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_ia_color.setObjectName("st_label_ia_color")
        self.gridLayout_3.addWidget(self.st_label_ia_color, 4, 0, 1, 1)
        self.st_sp_ia_color_r = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_ia_color_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_ia_color_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_ia_color_r.setMaximum(255)
        self.st_sp_ia_color_r.setProperty("value", 200)
        self.st_sp_ia_color_r.setObjectName("st_sp_ia_color_r")
        self.gridLayout_3.addWidget(self.st_sp_ia_color_r, 4, 1, 1, 1)
        self.st_sp_ia_color_g = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_ia_color_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_ia_color_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_ia_color_g.setMaximum(255)
        self.st_sp_ia_color_g.setProperty("value", 200)
        self.st_sp_ia_color_g.setObjectName("st_sp_ia_color_g")
        self.gridLayout_3.addWidget(self.st_sp_ia_color_g, 4, 2, 1, 1)
        self.st_sp_ia_color_b = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_ia_color_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_ia_color_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_ia_color_b.setMaximum(255)
        self.st_sp_ia_color_b.setProperty("value", 200)
        self.st_sp_ia_color_b.setObjectName("st_sp_ia_color_b")
        self.gridLayout_3.addWidget(self.st_sp_ia_color_b, 4, 3, 1, 1)
        self.st_label_vb_color = QtWidgets.QLabel(self.st_gbox_whl_itf)
        self.st_label_vb_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_vb_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_vb_color.setObjectName("st_label_vb_color")
        self.gridLayout_3.addWidget(self.st_label_vb_color, 5, 0, 1, 1)
        self.st_sp_vb_color_r = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_vb_color_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_vb_color_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_vb_color_r.setMaximum(255)
        self.st_sp_vb_color_r.setProperty("value", 230)
        self.st_sp_vb_color_r.setObjectName("st_sp_vb_color_r")
        self.gridLayout_3.addWidget(self.st_sp_vb_color_r, 5, 1, 1, 1)
        self.st_sp_vb_color_g = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_vb_color_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_vb_color_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_vb_color_g.setMaximum(255)
        self.st_sp_vb_color_g.setProperty("value", 230)
        self.st_sp_vb_color_g.setObjectName("st_sp_vb_color_g")
        self.gridLayout_3.addWidget(self.st_sp_vb_color_g, 5, 2, 1, 1)
        self.st_sp_vb_color_b = QtWidgets.QSpinBox(self.st_gbox_whl_itf)
        self.st_sp_vb_color_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_vb_color_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_vb_color_b.setMaximum(255)
        self.st_sp_vb_color_b.setProperty("value", 230)
        self.st_sp_vb_color_b.setObjectName("st_sp_vb_color_b")
        self.gridLayout_3.addWidget(self.st_sp_vb_color_b, 5, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(325, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 5, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 6, 0, 1, 1)
        self.verticalLayout.addWidget(self.st_gbox_whl_itf)
        self.st_gbox_img_itf = QtWidgets.QGroupBox(self.setti_interface)
        self.st_gbox_img_itf.setObjectName("st_gbox_img_itf")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.st_gbox_img_itf)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.st_label_tip_radius = QtWidgets.QLabel(self.st_gbox_img_itf)
        self.st_label_tip_radius.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_tip_radius.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_tip_radius.setObjectName("st_label_tip_radius")
        self.gridLayout_4.addWidget(self.st_label_tip_radius, 0, 0, 1, 1)
        self.st_p_tip_radius = QtWidgets.QDoubleSpinBox(self.st_gbox_img_itf)
        self.st_p_tip_radius.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_tip_radius.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_tip_radius.setSuffix("")
        self.st_p_tip_radius.setMinimum(0.01)
        self.st_p_tip_radius.setMaximum(2.0)
        self.st_p_tip_radius.setSingleStep(0.01)
        self.st_p_tip_radius.setProperty("value", 0.1)
        self.st_p_tip_radius.setObjectName("st_p_tip_radius")
        self.gridLayout_4.addWidget(self.st_p_tip_radius, 0, 1, 1, 1)
        self.st_label_half_sp = QtWidgets.QLabel(self.st_gbox_img_itf)
        self.st_label_half_sp.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_half_sp.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_half_sp.setObjectName("st_label_half_sp")
        self.gridLayout_4.addWidget(self.st_label_half_sp, 1, 0, 1, 1)
        self.st_p_half_sp = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_p_half_sp.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_half_sp.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_half_sp.setMaximum(20)
        self.st_p_half_sp.setProperty("value", 5)
        self.st_p_half_sp.setObjectName("st_p_half_sp")
        self.gridLayout_4.addWidget(self.st_p_half_sp, 1, 1, 1, 1)
        self.st_label_vs_color = QtWidgets.QLabel(self.st_gbox_img_itf)
        self.st_label_vs_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_vs_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_vs_color.setObjectName("st_label_vs_color")
        self.gridLayout_4.addWidget(self.st_label_vs_color, 2, 0, 1, 1)
        self.st_sp_vs_color_r = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_vs_color_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_vs_color_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_vs_color_r.setMaximum(255)
        self.st_sp_vs_color_r.setProperty("value", 100)
        self.st_sp_vs_color_r.setObjectName("st_sp_vs_color_r")
        self.gridLayout_4.addWidget(self.st_sp_vs_color_r, 2, 1, 1, 1)
        self.st_sp_vs_color_g = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_vs_color_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_vs_color_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_vs_color_g.setMaximum(255)
        self.st_sp_vs_color_g.setProperty("value", 100)
        self.st_sp_vs_color_g.setObjectName("st_sp_vs_color_g")
        self.gridLayout_4.addWidget(self.st_sp_vs_color_g, 2, 2, 1, 1)
        self.st_sp_vs_color_b = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_vs_color_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_vs_color_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_vs_color_b.setMaximum(255)
        self.st_sp_vs_color_b.setProperty("value", 100)
        self.st_sp_vs_color_b.setObjectName("st_sp_vs_color_b")
        self.gridLayout_4.addWidget(self.st_sp_vs_color_b, 2, 3, 1, 1)
        self.st_label_st_color = QtWidgets.QLabel(self.st_gbox_img_itf)
        self.st_label_st_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_st_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_st_color.setObjectName("st_label_st_color")
        self.gridLayout_4.addWidget(self.st_label_st_color, 3, 0, 1, 1)
        self.st_sp_st_color_r = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_st_color_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_st_color_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_st_color_r.setMaximum(255)
        self.st_sp_st_color_r.setProperty("value", 100)
        self.st_sp_st_color_r.setObjectName("st_sp_st_color_r")
        self.gridLayout_4.addWidget(self.st_sp_st_color_r, 3, 1, 1, 1)
        self.st_sp_st_color_g = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_st_color_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_st_color_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_st_color_g.setMaximum(255)
        self.st_sp_st_color_g.setProperty("value", 100)
        self.st_sp_st_color_g.setObjectName("st_sp_st_color_g")
        self.gridLayout_4.addWidget(self.st_sp_st_color_g, 3, 2, 1, 1)
        self.st_sp_st_color_b = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_st_color_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_st_color_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_st_color_b.setMaximum(255)
        self.st_sp_st_color_b.setProperty("value", 100)
        self.st_sp_st_color_b.setObjectName("st_sp_st_color_b")
        self.gridLayout_4.addWidget(self.st_sp_st_color_b, 3, 3, 1, 1)
        self.st_label_it_color = QtWidgets.QLabel(self.st_gbox_img_itf)
        self.st_label_it_color.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_it_color.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_it_color.setObjectName("st_label_it_color")
        self.gridLayout_4.addWidget(self.st_label_it_color, 4, 0, 1, 1)
        self.st_sp_it_color_r = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_it_color_r.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_it_color_r.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_it_color_r.setMaximum(255)
        self.st_sp_it_color_r.setProperty("value", 200)
        self.st_sp_it_color_r.setObjectName("st_sp_it_color_r")
        self.gridLayout_4.addWidget(self.st_sp_it_color_r, 4, 1, 1, 1)
        self.st_sp_it_color_g = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_it_color_g.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_it_color_g.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_it_color_g.setMaximum(255)
        self.st_sp_it_color_g.setProperty("value", 200)
        self.st_sp_it_color_g.setObjectName("st_sp_it_color_g")
        self.gridLayout_4.addWidget(self.st_sp_it_color_g, 4, 2, 1, 1)
        self.st_sp_it_color_b = QtWidgets.QSpinBox(self.st_gbox_img_itf)
        self.st_sp_it_color_b.setMinimumSize(QtCore.QSize(60, 0))
        self.st_sp_it_color_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_sp_it_color_b.setMaximum(255)
        self.st_sp_it_color_b.setProperty("value", 200)
        self.st_sp_it_color_b.setObjectName("st_sp_it_color_b")
        self.gridLayout_4.addWidget(self.st_sp_it_color_b, 4, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(333, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 4, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 5, 0, 1, 1)
        self.verticalLayout.addWidget(self.st_gbox_img_itf)
        self.setti_items.addTab(self.setti_interface, "")
        self.setti_rule = QtWidgets.QWidget()
        self.setti_rule.setObjectName("setti_rule")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.setti_rule)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.st_gbox_whl_rule = QtWidgets.QGroupBox(self.setti_rule)
        self.st_gbox_whl_rule.setObjectName("st_gbox_whl_rule")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.st_gbox_whl_rule)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.st_label_h_range_from = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_h_range_from.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_h_range_from.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_h_range_from.setObjectName("st_label_h_range_from")
        self.gridLayout_6.addWidget(self.st_label_h_range_from, 0, 0, 1, 1)
        self.st_dp_h_range_from = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_h_range_from.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_h_range_from.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_h_range_from.setMaximum(360.0)
        self.st_dp_h_range_from.setSingleStep(10.0)
        self.st_dp_h_range_from.setObjectName("st_dp_h_range_from")
        self.gridLayout_6.addWidget(self.st_dp_h_range_from, 0, 1, 1, 1)
        self.st_label_h_range_to = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_h_range_to.setMinimumSize(QtCore.QSize(30, 20))
        self.st_label_h_range_to.setMaximumSize(QtCore.QSize(30, 20))
        self.st_label_h_range_to.setObjectName("st_label_h_range_to")
        self.gridLayout_6.addWidget(self.st_label_h_range_to, 0, 2, 1, 1)
        self.st_dp_h_range_to = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_h_range_to.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_h_range_to.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_h_range_to.setMaximum(360.0)
        self.st_dp_h_range_to.setSingleStep(10.0)
        self.st_dp_h_range_to.setProperty("value", 360.0)
        self.st_dp_h_range_to.setObjectName("st_dp_h_range_to")
        self.gridLayout_6.addWidget(self.st_dp_h_range_to, 0, 3, 1, 1)
        self.st_label_s_range_from = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_s_range_from.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_s_range_from.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_s_range_from.setObjectName("st_label_s_range_from")
        self.gridLayout_6.addWidget(self.st_label_s_range_from, 1, 0, 1, 1)
        self.st_dp_s_range_from = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_s_range_from.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_s_range_from.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_s_range_from.setMaximum(1.0)
        self.st_dp_s_range_from.setSingleStep(0.1)
        self.st_dp_s_range_from.setObjectName("st_dp_s_range_from")
        self.gridLayout_6.addWidget(self.st_dp_s_range_from, 1, 1, 1, 1)
        self.st_label_s_range_to = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_s_range_to.setMinimumSize(QtCore.QSize(30, 20))
        self.st_label_s_range_to.setMaximumSize(QtCore.QSize(30, 20))
        self.st_label_s_range_to.setObjectName("st_label_s_range_to")
        self.gridLayout_6.addWidget(self.st_label_s_range_to, 1, 2, 1, 1)
        self.st_dp_s_range_to = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_s_range_to.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_s_range_to.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_s_range_to.setMaximum(1.0)
        self.st_dp_s_range_to.setSingleStep(0.1)
        self.st_dp_s_range_to.setProperty("value", 1.0)
        self.st_dp_s_range_to.setObjectName("st_dp_s_range_to")
        self.gridLayout_6.addWidget(self.st_dp_s_range_to, 1, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(294, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 1, 4, 1, 1)
        self.st_label_v_range_from = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_v_range_from.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_v_range_from.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_v_range_from.setObjectName("st_label_v_range_from")
        self.gridLayout_6.addWidget(self.st_label_v_range_from, 2, 0, 1, 1)
        self.st_dp_v_range_from = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_v_range_from.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_v_range_from.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_v_range_from.setMaximum(1.0)
        self.st_dp_v_range_from.setSingleStep(0.1)
        self.st_dp_v_range_from.setObjectName("st_dp_v_range_from")
        self.gridLayout_6.addWidget(self.st_dp_v_range_from, 2, 1, 1, 1)
        self.st_label_v_range_to = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_v_range_to.setMinimumSize(QtCore.QSize(30, 20))
        self.st_label_v_range_to.setMaximumSize(QtCore.QSize(30, 20))
        self.st_label_v_range_to.setObjectName("st_label_v_range_to")
        self.gridLayout_6.addWidget(self.st_label_v_range_to, 2, 2, 1, 1)
        self.st_dp_v_range_to = QtWidgets.QDoubleSpinBox(self.st_gbox_whl_rule)
        self.st_dp_v_range_to.setMinimumSize(QtCore.QSize(60, 0))
        self.st_dp_v_range_to.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_dp_v_range_to.setMaximum(1.0)
        self.st_dp_v_range_to.setSingleStep(0.1)
        self.st_dp_v_range_to.setProperty("value", 1.0)
        self.st_dp_v_range_to.setObjectName("st_dp_v_range_to")
        self.gridLayout_6.addWidget(self.st_dp_v_range_to, 2, 3, 1, 1)
        self.st_label_hm_rule = QtWidgets.QLabel(self.st_gbox_whl_rule)
        self.st_label_hm_rule.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_hm_rule.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_hm_rule.setObjectName("st_label_hm_rule")
        self.gridLayout_6.addWidget(self.st_label_hm_rule, 3, 0, 1, 1)
        self.st_comb_hm_rule = QtWidgets.QComboBox(self.st_gbox_whl_rule)
        self.st_comb_hm_rule.setMinimumSize(QtCore.QSize(120, 22))
        self.st_comb_hm_rule.setMaximumSize(QtCore.QSize(120, 22))
        self.st_comb_hm_rule.setObjectName("st_comb_hm_rule")
        self.st_comb_hm_rule.addItem("")
        self.st_comb_hm_rule.addItem("")
        self.st_comb_hm_rule.addItem("")
        self.st_comb_hm_rule.addItem("")
        self.st_comb_hm_rule.addItem("")
        self.st_comb_hm_rule.addItem("")
        self.st_comb_hm_rule.addItem("")
        self.st_comb_hm_rule.addItem("")
        self.gridLayout_6.addWidget(self.st_comb_hm_rule, 3, 1, 1, 2)
        self.st_cbox_press_move = QtWidgets.QCheckBox(self.st_gbox_whl_rule)
        self.st_cbox_press_move.setMinimumSize(QtCore.QSize(300, 22))
        self.st_cbox_press_move.setMaximumSize(QtCore.QSize(300, 22))
        self.st_cbox_press_move.setChecked(True)
        self.st_cbox_press_move.setObjectName("st_cbox_press_move")
        self.gridLayout_6.addWidget(self.st_cbox_press_move, 4, 0, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 5, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.st_gbox_whl_rule)
        self.st_gbox_img_rule = QtWidgets.QGroupBox(self.setti_rule)
        self.st_gbox_img_rule.setObjectName("st_gbox_img_rule")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.st_gbox_img_rule)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.st_label_graph_types = QtWidgets.QLabel(self.st_gbox_img_rule)
        self.st_label_graph_types.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_graph_types.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_graph_types.setObjectName("st_label_graph_types")
        self.gridLayout_5.addWidget(self.st_label_graph_types, 0, 0, 1, 1)
        self.st_cobox_graph_types_0 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_graph_types_0.setMinimumSize(QtCore.QSize(120, 22))
        self.st_cobox_graph_types_0.setMaximumSize(QtCore.QSize(120, 22))
        self.st_cobox_graph_types_0.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.st_cobox_graph_types_0.setObjectName("st_cobox_graph_types_0")
        self.st_cobox_graph_types_0.addItem("")
        self.st_cobox_graph_types_0.addItem("")
        self.st_cobox_graph_types_0.addItem("")
        self.st_cobox_graph_types_0.addItem("")
        self.st_cobox_graph_types_0.addItem("")
        self.st_cobox_graph_types_0.addItem("")
        self.st_cobox_graph_types_0.addItem("")
        self.st_cobox_graph_types_0.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_graph_types_0, 0, 1, 1, 1)
        self.st_cobox_graph_types_1 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_graph_types_1.setMinimumSize(QtCore.QSize(120, 22))
        self.st_cobox_graph_types_1.setMaximumSize(QtCore.QSize(120, 22))
        self.st_cobox_graph_types_1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.st_cobox_graph_types_1.setObjectName("st_cobox_graph_types_1")
        self.st_cobox_graph_types_1.addItem("")
        self.st_cobox_graph_types_1.addItem("")
        self.st_cobox_graph_types_1.addItem("")
        self.st_cobox_graph_types_1.addItem("")
        self.st_cobox_graph_types_1.addItem("")
        self.st_cobox_graph_types_1.addItem("")
        self.st_cobox_graph_types_1.addItem("")
        self.st_cobox_graph_types_1.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_graph_types_1, 0, 2, 1, 1)
        self.st_cobox_graph_types_2 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_graph_types_2.setMinimumSize(QtCore.QSize(120, 22))
        self.st_cobox_graph_types_2.setMaximumSize(QtCore.QSize(120, 22))
        self.st_cobox_graph_types_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.st_cobox_graph_types_2.setObjectName("st_cobox_graph_types_2")
        self.st_cobox_graph_types_2.addItem("")
        self.st_cobox_graph_types_2.addItem("")
        self.st_cobox_graph_types_2.addItem("")
        self.st_cobox_graph_types_2.addItem("")
        self.st_cobox_graph_types_2.addItem("")
        self.st_cobox_graph_types_2.addItem("")
        self.st_cobox_graph_types_2.addItem("")
        self.st_cobox_graph_types_2.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_graph_types_2, 1, 1, 1, 1)
        self.st_cobox_graph_types_3 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_graph_types_3.setMinimumSize(QtCore.QSize(120, 22))
        self.st_cobox_graph_types_3.setMaximumSize(QtCore.QSize(120, 22))
        self.st_cobox_graph_types_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.st_cobox_graph_types_3.setObjectName("st_cobox_graph_types_3")
        self.st_cobox_graph_types_3.addItem("")
        self.st_cobox_graph_types_3.addItem("")
        self.st_cobox_graph_types_3.addItem("")
        self.st_cobox_graph_types_3.addItem("")
        self.st_cobox_graph_types_3.addItem("")
        self.st_cobox_graph_types_3.addItem("")
        self.st_cobox_graph_types_3.addItem("")
        self.st_cobox_graph_types_3.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_graph_types_3, 1, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 1, 3, 1, 1)
        self.st_label_graph_chls = QtWidgets.QLabel(self.st_gbox_img_rule)
        self.st_label_graph_chls.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_graph_chls.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_graph_chls.setObjectName("st_label_graph_chls")
        self.gridLayout_5.addWidget(self.st_label_graph_chls, 2, 0, 1, 1)
        self.st_cobox_graph_chls_0 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_graph_chls_0.setMinimumSize(QtCore.QSize(80, 22))
        self.st_cobox_graph_chls_0.setMaximumSize(QtCore.QSize(80, 22))
        self.st_cobox_graph_chls_0.setObjectName("st_cobox_graph_chls_0")
        self.st_cobox_graph_chls_0.addItem("")
        self.st_cobox_graph_chls_0.addItem("")
        self.st_cobox_graph_chls_0.addItem("")
        self.st_cobox_graph_chls_0.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_graph_chls_0, 2, 1, 1, 1)
        self.st_cobox_graph_chls_1 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_graph_chls_1.setMinimumSize(QtCore.QSize(80, 22))
        self.st_cobox_graph_chls_1.setMaximumSize(QtCore.QSize(80, 22))
        self.st_cobox_graph_chls_1.setObjectName("st_cobox_graph_chls_1")
        self.st_cobox_graph_chls_1.addItem("")
        self.st_cobox_graph_chls_1.addItem("")
        self.st_cobox_graph_chls_1.addItem("")
        self.st_cobox_graph_chls_1.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_graph_chls_1, 2, 2, 1, 1)
        self.st_cobox_graph_chls_2 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_graph_chls_2.setMinimumSize(QtCore.QSize(80, 22))
        self.st_cobox_graph_chls_2.setMaximumSize(QtCore.QSize(80, 22))
        self.st_cobox_graph_chls_2.setObjectName("st_cobox_graph_chls_2")
        self.st_cobox_graph_chls_2.addItem("")
        self.st_cobox_graph_chls_2.addItem("")
        self.st_cobox_graph_chls_2.addItem("")
        self.st_cobox_graph_chls_2.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_graph_chls_2, 3, 1, 1, 1)
        self.st_cobox_graph_chls_3 = QtWidgets.QComboBox(self.st_gbox_img_rule)
        self.st_cobox_graph_chls_3.setMinimumSize(QtCore.QSize(80, 22))
        self.st_cobox_graph_chls_3.setMaximumSize(QtCore.QSize(80, 22))
        self.st_cobox_graph_chls_3.setObjectName("st_cobox_graph_chls_3")
        self.st_cobox_graph_chls_3.addItem("")
        self.st_cobox_graph_chls_3.addItem("")
        self.st_cobox_graph_chls_3.addItem("")
        self.st_cobox_graph_chls_3.addItem("")
        self.gridLayout_5.addWidget(self.st_cobox_graph_chls_3, 3, 2, 1, 1)
        self.st_label_zoom_step = QtWidgets.QLabel(self.st_gbox_img_rule)
        self.st_label_zoom_step.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_zoom_step.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_zoom_step.setObjectName("st_label_zoom_step")
        self.gridLayout_5.addWidget(self.st_label_zoom_step, 4, 0, 1, 1)
        self.st_p_zoom_step = QtWidgets.QDoubleSpinBox(self.st_gbox_img_rule)
        self.st_p_zoom_step.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_zoom_step.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_zoom_step.setMinimum(1.0)
        self.st_p_zoom_step.setMaximum(10.0)
        self.st_p_zoom_step.setSingleStep(0.05)
        self.st_p_zoom_step.setProperty("value", 1.3)
        self.st_p_zoom_step.setObjectName("st_p_zoom_step")
        self.gridLayout_5.addWidget(self.st_p_zoom_step, 4, 1, 1, 1)
        self.st_label_move_step = QtWidgets.QLabel(self.st_gbox_img_rule)
        self.st_label_move_step.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_move_step.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_move_step.setObjectName("st_label_move_step")
        self.gridLayout_5.addWidget(self.st_label_move_step, 5, 0, 1, 1)
        self.st_p_move_step = QtWidgets.QSpinBox(self.st_gbox_img_rule)
        self.st_p_move_step.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_move_step.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_move_step.setMinimum(0)
        self.st_p_move_step.setMaximum(50)
        self.st_p_move_step.setProperty("value", 5)
        self.st_p_move_step.setObjectName("st_p_move_step")
        self.gridLayout_5.addWidget(self.st_p_move_step, 5, 1, 1, 1)
        self.st_label_select_dist = QtWidgets.QLabel(self.st_gbox_img_rule)
        self.st_label_select_dist.setMinimumSize(QtCore.QSize(200, 20))
        self.st_label_select_dist.setMaximumSize(QtCore.QSize(200, 20))
        self.st_label_select_dist.setObjectName("st_label_select_dist")
        self.gridLayout_5.addWidget(self.st_label_select_dist, 6, 0, 1, 1)
        self.st_p_select_dist = QtWidgets.QSpinBox(self.st_gbox_img_rule)
        self.st_p_select_dist.setMinimumSize(QtCore.QSize(60, 0))
        self.st_p_select_dist.setMaximumSize(QtCore.QSize(60, 16777215))
        self.st_p_select_dist.setMinimum(1)
        self.st_p_select_dist.setMaximum(100)
        self.st_p_select_dist.setProperty("value", 10)
        self.st_p_select_dist.setObjectName("st_p_select_dist")
        self.gridLayout_5.addWidget(self.st_p_select_dist, 6, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 7, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.st_gbox_img_rule)
        self.setti_items.addTab(self.setti_rule, "")
        self.gridLayout.addWidget(self.setti_items, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.setti_items.setCurrentIndex(0)
        self.st_cobox_graph_types_1.setCurrentIndex(7)
        self.st_cobox_graph_types_2.setCurrentIndex(7)
        self.st_cobox_graph_types_3.setCurrentIndex(7)
        self.st_cobox_graph_chls_1.setCurrentIndex(1)
        self.st_cobox_graph_chls_2.setCurrentIndex(2)
        self.st_cobox_graph_chls_3.setCurrentIndex(3)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.st_gbox_sqr_itf.setTitle(_translate("Dialog", "Color Square"))
        self.st_label_widratio.setText(_translate("Dialog", "Color square length"))
        self.st_gbox_whl_itf.setTitle(_translate("Dialog", "Color wheel"))
        self.st_label_raduis.setText(_translate("Dialog", "Color wheel radius"))
        self.st_label_color_radius.setText(_translate("Dialog", "Color tag radius"))
        self.st_label_bar_widratio.setText(_translate("Dialog", "Color bar length"))
        self.st_label_at_color.setText(_translate("Dialog", "Active tag color"))
        self.st_label_ia_color.setText(_translate("Dialog", "Inactive tag color"))
        self.st_label_vb_color.setText(_translate("Dialog", "Bar color"))
        self.st_gbox_img_itf.setTitle(_translate("Dialog", "Graph view"))
        self.st_label_tip_radius.setText(_translate("Dialog", "Drag hint radius"))
        self.st_label_half_sp.setText(_translate("Dialog", "Graph separation width"))
        self.st_label_vs_color.setText(_translate("Dialog", "Drag hint color"))
        self.st_label_st_color.setText(_translate("Dialog", "Selection color"))
        self.st_label_it_color.setText(_translate("Dialog", "Reference color"))
        self.setti_items.setTabText(self.setti_items.indexOf(self.setti_interface), _translate("Dialog", "Interface"))
        self.st_gbox_whl_rule.setTitle(_translate("Dialog", "Color wheel"))
        self.st_label_h_range_from.setText(_translate("Dialog", "H range from"))
        self.st_label_h_range_to.setText(_translate("Dialog", "to"))
        self.st_label_s_range_from.setText(_translate("Dialog", "S range from"))
        self.st_label_s_range_to.setText(_translate("Dialog", "to"))
        self.st_label_v_range_from.setText(_translate("Dialog", "V range from"))
        self.st_label_v_range_to.setText(_translate("Dialog", "to"))
        self.st_label_hm_rule.setText(_translate("Dialog", "Harmony rule"))
        self.st_comb_hm_rule.setItemText(0, _translate("Dialog", "Analogous"))
        self.st_comb_hm_rule.setItemText(1, _translate("Dialog", "Monochromatic"))
        self.st_comb_hm_rule.setItemText(2, _translate("Dialog", "Triad"))
        self.st_comb_hm_rule.setItemText(3, _translate("Dialog", "Tetrad"))
        self.st_comb_hm_rule.setItemText(4, _translate("Dialog", "Pentad"))
        self.st_comb_hm_rule.setItemText(5, _translate("Dialog", "Complementary"))
        self.st_comb_hm_rule.setItemText(6, _translate("Dialog", "Shades"))
        self.st_comb_hm_rule.setItemText(7, _translate("Dialog", "Custom"))
        self.st_cbox_press_move.setText(_translate("Dialog", "Press and select"))
        self.st_gbox_img_rule.setTitle(_translate("Dialog", "Image view"))
        self.st_label_graph_types.setText(_translate("Dialog", "Graph types"))
        self.st_cobox_graph_types_0.setItemText(0, _translate("Dialog", "RGB-Normal"))
        self.st_cobox_graph_types_0.setItemText(1, _translate("Dialog", "RGB-Vertical"))
        self.st_cobox_graph_types_0.setItemText(2, _translate("Dialog", "RGB-Horizontal"))
        self.st_cobox_graph_types_0.setItemText(3, _translate("Dialog", "RGB-Final"))
        self.st_cobox_graph_types_0.setItemText(4, _translate("Dialog", "HSV-Normal"))
        self.st_cobox_graph_types_0.setItemText(5, _translate("Dialog", "HSV-Vertical"))
        self.st_cobox_graph_types_0.setItemText(6, _translate("Dialog", "HSV-Horizontal"))
        self.st_cobox_graph_types_0.setItemText(7, _translate("Dialog", "HSV-Final"))
        self.st_cobox_graph_types_1.setItemText(0, _translate("Dialog", "RGB-Normal"))
        self.st_cobox_graph_types_1.setItemText(1, _translate("Dialog", "RGB-Vertical"))
        self.st_cobox_graph_types_1.setItemText(2, _translate("Dialog", "RGB-Horizontal"))
        self.st_cobox_graph_types_1.setItemText(3, _translate("Dialog", "RGB-Final"))
        self.st_cobox_graph_types_1.setItemText(4, _translate("Dialog", "HSV-Normal"))
        self.st_cobox_graph_types_1.setItemText(5, _translate("Dialog", "HSV-Vertical"))
        self.st_cobox_graph_types_1.setItemText(6, _translate("Dialog", "HSV-Horizontal"))
        self.st_cobox_graph_types_1.setItemText(7, _translate("Dialog", "HSV-Final"))
        self.st_cobox_graph_types_2.setItemText(0, _translate("Dialog", "RGB-Normal"))
        self.st_cobox_graph_types_2.setItemText(1, _translate("Dialog", "RGB-Vertical"))
        self.st_cobox_graph_types_2.setItemText(2, _translate("Dialog", "RGB-Horizontal"))
        self.st_cobox_graph_types_2.setItemText(3, _translate("Dialog", "RGB-Final"))
        self.st_cobox_graph_types_2.setItemText(4, _translate("Dialog", "HSV-Normal"))
        self.st_cobox_graph_types_2.setItemText(5, _translate("Dialog", "HSV-Vertical"))
        self.st_cobox_graph_types_2.setItemText(6, _translate("Dialog", "HSV-Horizontal"))
        self.st_cobox_graph_types_2.setItemText(7, _translate("Dialog", "HSV-Final"))
        self.st_cobox_graph_types_3.setItemText(0, _translate("Dialog", "RGB-Normal"))
        self.st_cobox_graph_types_3.setItemText(1, _translate("Dialog", "RGB-Vertical"))
        self.st_cobox_graph_types_3.setItemText(2, _translate("Dialog", "RGB-Horizontal"))
        self.st_cobox_graph_types_3.setItemText(3, _translate("Dialog", "RGB-Final"))
        self.st_cobox_graph_types_3.setItemText(4, _translate("Dialog", "HSV-Normal"))
        self.st_cobox_graph_types_3.setItemText(5, _translate("Dialog", "HSV-Vertical"))
        self.st_cobox_graph_types_3.setItemText(6, _translate("Dialog", "HSV-Horizontal"))
        self.st_cobox_graph_types_3.setItemText(7, _translate("Dialog", "HSV-Final"))
        self.st_label_graph_chls.setText(_translate("Dialog", "Graph channels"))
        self.st_cobox_graph_chls_0.setItemText(0, _translate("Dialog", "All"))
        self.st_cobox_graph_chls_0.setItemText(1, _translate("Dialog", "1 R/H"))
        self.st_cobox_graph_chls_0.setItemText(2, _translate("Dialog", "2 G/S"))
        self.st_cobox_graph_chls_0.setItemText(3, _translate("Dialog", "3 B/V"))
        self.st_cobox_graph_chls_1.setItemText(0, _translate("Dialog", "All"))
        self.st_cobox_graph_chls_1.setItemText(1, _translate("Dialog", "1 R/H"))
        self.st_cobox_graph_chls_1.setItemText(2, _translate("Dialog", "2 G/S"))
        self.st_cobox_graph_chls_1.setItemText(3, _translate("Dialog", "3 B/V"))
        self.st_cobox_graph_chls_2.setItemText(0, _translate("Dialog", "All"))
        self.st_cobox_graph_chls_2.setItemText(1, _translate("Dialog", "1 R/H"))
        self.st_cobox_graph_chls_2.setItemText(2, _translate("Dialog", "2 G/S"))
        self.st_cobox_graph_chls_2.setItemText(3, _translate("Dialog", "3 B/V"))
        self.st_cobox_graph_chls_3.setItemText(0, _translate("Dialog", "All"))
        self.st_cobox_graph_chls_3.setItemText(1, _translate("Dialog", "1 R/H"))
        self.st_cobox_graph_chls_3.setItemText(2, _translate("Dialog", "2 G/S"))
        self.st_cobox_graph_chls_3.setItemText(3, _translate("Dialog", "3 B/V"))
        self.st_label_zoom_step.setText(_translate("Dialog", "Zoom step"))
        self.st_label_move_step.setText(_translate("Dialog", "Move step"))
        self.st_label_select_dist.setText(_translate("Dialog", "Selection distance"))
        self.setti_items.setTabText(self.setti_items.indexOf(self.setti_rule), _translate("Dialog", "Rule"))


